// Addapplicantform.tsx
//
// Applicant Info form — Freight-style:
//  • forwardRef + useImperativeHandle → page header "Save as Draft" / "Submit"
//    buttons call saveDraft() / submit()
//  • SectionPanel / Field from shared Formblocks
//  • toast for validation / API feedback (no inline alert banners)
//  • No bottom button row — Close / Save as Draft / Submit live in the page header

import { IdCard, MessageSquare } from "lucide-react";
import { forwardRef, useCallback, useEffect, useImperativeHandle, useState } from "react";
import { executeDynamicMutationColumn90, getDynamicLookup } from "../../api/lookups";
import { useToast } from "../../components/ui/AlertToast";
import { Button } from "../../components/ui/Button";
import { Dialog } from "../../components/ui/Dialog";
import { Field, SectionPanel } from "../../components/ui/Formblocks";
import { Input } from "../../components/ui/Input";
import { Select } from "../../components/ui/Select";
import { useAuth } from "../../state/AuthContext";

/* ✅ Exposed to the parent (header buttons) */
export type ApplicantFormHandle = {
  saveDraft: () => Promise<void>;
  submit: () => void;
};

export type TApplicantInfo = {
  doc_no?: string | number | null;
  doc_type?: string;
  doc_date?: string;
  doc_ref_no?: string;
  cand_no?: string;
  cand_name?: string;
  pos_appl_for?: string;
  dept?: string;
  intvr_name?: string;
  intrvw_date?: string;
  hire_flag?: string;
  dept_head_comment1?: string;
  sign_1?: string;
  dept_head_comment2?: string;
  sign_2?: string;
  admin_hr_comment?: string;
  sign_3?: string;
  ceo_comment?: string;
  sign_4?: string;
};

type DeptOption = {
  dept_code: string;
  dept_short_name: string;
};

export type FormMode = "add" | "edit" | "view";

type Props = {
  mode: FormMode;
  existingData?: Partial<TApplicantInfo> | null;
  onClose: (shouldRefetch?: boolean) => void;
  /** lets the page header disable its buttons while a save is in flight */
  onSavingChange?: (saving: boolean) => void;
};

function toDate(value: unknown): string {
  if (!value) return "";
  const normalized = String(value).trim();
  const date = new Date(normalized);
  return Number.isNaN(date.getTime()) ? "" : date.toISOString().slice(0, 10);
}

const today = new Date().toISOString().slice(0, 10);

// doc_no / doc_type are tracked but never surfaced as fields — doc_no is
// autogenerated by the backend and doc_type is always "INT" (interview).
const EMPTY: TApplicantInfo = {
  doc_no: null,
  doc_type: "INT",
  doc_date: today,
  doc_ref_no: "",
  cand_no: "",
  cand_name: "",
  pos_appl_for: "",
  dept: "",
  intvr_name: "",
  intrvw_date: "",
  hire_flag: "",
  dept_head_comment1: "",
  sign_1: "",
  dept_head_comment2: "",
  sign_2: "",
  admin_hr_comment: "",
  sign_3: "",
  ceo_comment: "",
  sign_4: "",
};

const buildInitial = (mode: FormMode, existingData?: Partial<TApplicantInfo> | null): TApplicantInfo =>
  mode !== "add" && existingData
    ? {
        ...EMPTY,
        ...existingData,
        doc_date: toDate(existingData.doc_date) || today,
        intrvw_date: toDate(existingData.intrvw_date),
      }
    : { ...EMPTY };

/* ─────────────────────────────────────────────────────────────
   Main Form (forwardRef so parent can trigger save / submit)
   ───────────────────────────────────────────────────────────── */
export const AddApplicantForm = forwardRef<ApplicantFormHandle, Props>(function AddApplicantForm(
  { mode, existingData, onClose, onSavingChange },
  ref,
) {
  const { user } = useAuth();
  const { toast } = useToast();
  const readonly = mode === "view";
  const isEdit = mode === "edit";

  const [form, setForm] = useState<TApplicantInfo>(() => buildInitial(mode, existingData));
  const [errors, setErrors] = useState<Partial<Record<keyof TApplicantInfo, string>>>({});
  const [saving, setSaving] = useState(false);
  const [deptList, setDeptList] = useState<DeptOption[]>([]);
  const [confirmSubmitOpen, setConfirmSubmitOpen] = useState(false);

  // ── Load departments — parameter "HR_CAM_DEPARTMENT_DEPTCODE" ──────────
  const loadDepts = useCallback(async () => {
    try {
      const res = await getDynamicLookup({
        parameter: "HR_CAM_DEPARTMENT_DEPTCODE",
        loginid: user?.loginid ?? "",
        code1: user?.company_code ?? "",
        code2: "",
        code3: "",
        code4: "",
        number1: 0,
        number2: 0,
        number3: 0,
        number4: 0,
        date1: null,
        date2: null,
        date3: null,
        date4: null,
      });
      const list = Array.isArray(res) ? (res as Record<string, unknown>[]) : [];
      setDeptList(
        list.map((d) => ({
          dept_code: String(d.DEPT_CODE ?? d.dept_code ?? ""),
          dept_short_name: String(d.DEPT_SHORT_NAME ?? d.dept_short_name ?? ""),
        })),
      );
    } catch {
      // non-critical; dropdown will simply be empty
    }
  }, [user?.loginid, user?.company_code]);

  useEffect(() => {
    void loadDepts();
  }, [loadDepts]);

  const set = (field: keyof TApplicantInfo, value: unknown) =>
    setForm((prev) => ({ ...prev, [field]: value }));

  // ── Validation ───────────────────────────────────────────────────────────
  const validate = (): string | null => {
    const next: Partial<Record<keyof TApplicantInfo, string>> = {};
    if (!form.doc_date) next.doc_date = "Doc Date is required";
    if (!form.cand_name?.trim()) next.cand_name = "Candidate Name is required";
    if (!form.dept?.trim()) next.dept = "Department is required";
    setErrors(next);
    return Object.values(next)[0] ?? null;
  };

  // ── Save — parameter "HR_APPLICANT_INFO_INS_UPD" ───────────────────────
  const handleSave = async () => {
    const error = validate();
    if (error) {
      toast.warning(error);
      return;
    }

    setSaving(true);
    onSavingChange?.(true);
    try {
      const docNo =
        isEdit && form.doc_no !== "" && form.doc_no != null ? Number(form.doc_no) : undefined;

      await executeDynamicMutationColumn90({
        parameter: "HR_APPLICANT_INFO_INS_UPD",
        loginid: user?.loginid ?? "",
        val1s1: user?.company_code ?? "",
        val1s2: form.doc_type ?? "INT",
        val1n1: docNo,
        val1s3: form.doc_ref_no || "",
        val1s4: form.cand_no || "",
        val1s5: form.cand_name || "",
        val1s6: form.pos_appl_for || "",
        val1s7: form.dept || "",
        val1s8: form.intvr_name || "",
        val1s9: form.intrvw_date ? toDate(form.intrvw_date) : "",
        val1s10: form.hire_flag || "",
        val1s11: form.dept_head_comment1 || "",
        val1s12: form.sign_1 || "",
        val1s13: form.dept_head_comment2 || "",
        val1s14: form.sign_2 || "",
        val1s15: form.admin_hr_comment || "",
        val1s16: form.sign_3 || "",
        val1s17: form.ceo_comment || "",
        val1s18: form.sign_4 || "",
        val1s19: toDate(form.doc_date),
        val1s20: isEdit ? "UPDATE" : "INSERT",
      });
      toast.success(isEdit ? "Applicant updated successfully" : "Applicant saved successfully");
      onClose(true);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Unable to save applicant record");
    } finally {
      setSaving(false);
      onSavingChange?.(false);
    }
  };

  // Submit = validate first, then confirm, then the same save call
  const handleSubmitClick = () => {
    const error = validate();
    if (error) {
      toast.warning(error);
      return;
    }
    setConfirmSubmitOpen(true);
  };

  const confirmSubmit = async () => {
    setConfirmSubmitOpen(false);
    await handleSave();
  };

  /* ✅ Expose to parent */
  useImperativeHandle(ref, () => ({
    saveDraft: handleSave,
    submit: handleSubmitClick,
  }));

  const text = (key: keyof TApplicantInfo, type: "text" | "date" = "text") => ({
    type,
    disabled: readonly,
    value: String(form[key] ?? ""),
    onChange: (e: React.ChangeEvent<HTMLInputElement>) => set(key, e.target.value),
  });

  // ── UI ───────────────────────────────────────────────────────────────────
  return (
    <div className="freight-workspace-ui freight-dense-form freight-ui-standard flex flex-col gap-2">
      <SectionPanel title="Candidate & Interview Details" icon={IdCard}>
        <div className="grid gap-3 md:grid-cols-4">
          <Field label="Doc Date" required error={errors.doc_date}>
            <Input {...text("doc_date", "date")} />
          </Field>
          <Field label="Doc Ref No">
            <Input {...text("doc_ref_no")} />
          </Field>
          <Field label="Candidate Name" required error={errors.cand_name}>
            <Input {...text("cand_name")} />
          </Field>
          <Field label="Department" required error={errors.dept}>
            <Select
              disabled={readonly}
              value={
                deptList.some((d) => d.dept_code === String(form.dept ?? ""))
                  ? String(form.dept ?? "")
                  : ""
              }
              onChange={(e) => set("dept", e.target.value)}
            >
              <option value="">-- Select Department --</option>
              {deptList.map((d) => (
                <option key={d.dept_code} value={d.dept_code}>
                  {d.dept_code} - {d.dept_short_name}
                </option>
              ))}
            </Select>
          </Field>

          <Field label="Position Applied">
            <Input {...text("pos_appl_for")} />
          </Field>
          <Field label="Interviewer Name">
            <Input {...text("intvr_name")} />
          </Field>
          <Field label="Interview Date">
            <Input {...text("intrvw_date", "date")} />
          </Field>
          <Field label="Hire">
            <Select
              disabled={readonly}
              value={form.hire_flag ?? ""}
              onChange={(e) => set("hire_flag", e.target.value)}
            >
              <option value="">-- Select --</option>
              <option value="Y">Yes</option>
              <option value="N">No</option>
            </Select>
          </Field>
        </div>
      </SectionPanel>

      <SectionPanel title="Comments & Signatories" icon={MessageSquare}>
        <div className="grid gap-3 md:grid-cols-2">
          <Field label="Dept Head Comment 1">
            <Input {...text("dept_head_comment1")} />
          </Field>
          <Field label="Sign 1">
            <Input {...text("sign_1")} />
          </Field>
          <Field label="Dept Head Comment 2">
            <Input {...text("dept_head_comment2")} />
          </Field>
          <Field label="Sign 2">
            <Input {...text("sign_2")} />
          </Field>
          <Field label="Admin HR Comment">
            <Input {...text("admin_hr_comment")} />
          </Field>
          <Field label="Sign 3">
            <Input {...text("sign_3")} />
          </Field>
          <Field label="CEO Comment">
            <Input {...text("ceo_comment")} />
          </Field>
          <Field label="Sign 4">
            <Input {...text("sign_4")} />
          </Field>
        </div>
      </SectionPanel>

      {/* ── Submit confirmation ── */}
      <Dialog
        open={confirmSubmitOpen}
        title="Submit"
        description="Are you sure you want to Submit?"
        compact
        onClose={() => setConfirmSubmitOpen(false)}
        footer={
          <>
            <Button variant="outline" onClick={() => setConfirmSubmitOpen(false)}>
              No
            </Button>
            <Button onClick={() => void confirmSubmit()} disabled={saving}>
              Yes
            </Button>
          </>
        }
      >
        <p className="m-0 text-sm text-muted-foreground">
          This will submit the applicant record for{" "}
          <strong>{form.cand_name || "(new candidate)"}</strong>.
        </p>
      </Dialog>
    </div>
  );
});