import { Save, Send, X } from "lucide-react";
import type { CSSProperties } from "react";
import { useCallback, useEffect, useState } from "react";
import { executeDynamicMutation, executeDynamicMutationColumn90, getDynamicLookup } from "../../api/lookups";
import { Button } from "../../components/ui/Button";
import { Dialog } from "../../components/ui/Dialog";
import { Input } from "../../components/ui/Input";
import { LookupField } from "../../components/ui/LookupField";
import { useAuth } from "../../state/AuthContext";

// ── Types ─────────────────────────────────────────────────────────────────────

export type TEmployeeTransfer = {
  doc_no?: string | number | null;
  doc_type?: string;
  company_code?: string;
  div_code?: string;
  div_name?: string;
  dept_code?: string;
  dept_name?: string;
  section_code?: string;
  section_name?: string;
  employee_id?: string;
  employee_name?: string;
  desg_code?: string;
  desg_name?: string;
  company_code_to?: string;
  div_code_to?: string;
  div_name_to?: string;
  dept_code_to?: string;
  dept_name_to?: string;
  section_code_to?: string;
  section_name_to?: string;
  desg_code_to?: string;
  desg_name_to?: string;
  remarks?: string;
  approved?: string;
  user_dt?: string;
};

type DivisionOption = { div_code: string; div_name: string };
type DeptOption = { dept_code: string; dept_name: string };
type SectionOption = { section_code: string; section_name: string };
// The employee list lookup (EDUCATION_QUALIFICATION_HR_EMPLOYEE_LIST_WITH_MANAGER)
// only returns EMPLOYEE_ID + EMPLOYEE_NAME — no org/designation codes. Those
// are fetched separately (see loadEmployeeDetail) the moment an employee is
// picked, so this option type intentionally stays minimal.
type EmployeeOption = { employee_id: string; employee_name: string };
type DesignationOption = { desg_code: string; desg_name: string };

type FormMode = "add" | "edit" | "view";

type Props = {
  mode: FormMode;
  existingData?: Partial<TEmployeeTransfer>;
  onClose: (shouldRefetch?: boolean) => void;
};

// doc_no / doc_type are tracked but never surfaced as editable fields —
// doc_no is autogenerated by the backend and doc_type is fixed, same idea
// as the applicant form.
const EMPTY: TEmployeeTransfer = {
  doc_no: null,
  doc_type: "ETR",
  company_code: "",
  div_code: "",
  div_name: "",
  dept_code: "",
  dept_name: "",
  section_code: "",
  section_name: "",
  employee_id: "",
  employee_name: "",
  desg_code: "",
  desg_name: "",
  company_code_to: "",
  div_code_to: "",
  div_name_to: "",
  dept_code_to: "",
  dept_name_to: "",
  section_code_to: "",
  section_name_to: "",
  desg_code_to: "",
  desg_name_to: "",
  remarks: "",
  approved: "N",
  user_dt: new Date().toISOString().slice(0, 10),
};

function buildParams(
  parameter: string,
  loginid: string,
  companyCode: string,
  code2 = "",
  code3 = "",
  code4 = "",
) {
  return {
    parameter,
    loginid,
    code1: companyCode,
    code2,
    code3,
    code4,
    number1: 0,
    number2: 0,
    number3: 0,
    number4: 0,
    date1: null,
    date2: null,
    date3: null,
    date4: null,
  };
}

// "CODE - Name" when a name is known, otherwise just the bare code.
function formatCodeName(code?: string, name?: string): string {
  if (!code) return "";
  return name && name !== code ? `${code} - ${name}` : code;
}

export function AddEmployeeTransferForm({ mode, existingData, onClose }: Props) {
  const { user } = useAuth();
  const readonly = mode === "view";
  const isEdit = mode === "edit";
  const loginid = user?.loginid ?? "";
  const companyCode = user?.company_code ?? "";
  const companyName = user?.company_name ?? companyCode;

  const [form, setForm] = useState<TEmployeeTransfer>({
    ...EMPTY,
    company_code: companyCode,
    company_code_to: companyCode,
  });
  const [errors, setErrors] = useState<Partial<Record<keyof TEmployeeTransfer, string>>>({});
  const [saving, setSaving] = useState(false);
  const [apiError, setApiError] = useState("");
  const [confirmSubmitOpen, setConfirmSubmitOpen] = useState(false);

  // ── From-side filters — only meaningful while no employee is picked yet;
  // they narrow the Employee dropdown, same as the optional
  // AND DIV_CODE=... / AND DEPT_CODE=... in the PB 'p_5' query. ───────────
  const [division, setDivision] = useState<DivisionOption | null>(null);
  const [department, setDepartment] = useState<DeptOption | null>(null);
  const [section, setSection] = useState<SectionOption | null>(null);
  const [employee, setEmployee] = useState<EmployeeOption | null>(null);
  const [loadingEmpDetail, setLoadingEmpDetail] = useState(false);

  // ── To-side (transfer destination) state — unchanged ────────────────────
  const [divisionTo, setDivisionTo] = useState<DivisionOption | null>(null);
  const [departmentTo, setDepartmentTo] = useState<DeptOption | null>(null);
  const [sectionTo, setSectionTo] = useState<SectionOption | null>(null);
  const [designationTo, setDesignationTo] = useState<DesignationOption | null>(null);

  // Once an employee is selected (add mode) or we're editing/viewing an
  // existing row, the From-side org fields switch from dropdowns to
  // read-only text — there's nothing left to "select", it's just what
  // that employee's record says.
  const showOrgAsText = isEdit || readonly || Boolean(employee?.employee_id);

  const set = (field: keyof TEmployeeTransfer, value: unknown) =>
    setForm((prev) => ({ ...prev, [field]: value }));

  // ── Populate on edit / view ──────────────────────────────────────────────
  useEffect(() => {
    if ((isEdit || readonly) && existingData) {
      setForm({ ...EMPTY, company_code: companyCode, company_code_to: companyCode, ...existingData });

      setEmployee(
        existingData.employee_id
          ? { employee_id: existingData.employee_id, employee_name: existingData.employee_name ?? "" }
          : null,
      );

      setDivisionTo(
        existingData.div_code_to
          ? { div_code: existingData.div_code_to, div_name: existingData.div_name_to ?? existingData.div_code_to }
          : null,
      );
      setDepartmentTo(
        existingData.dept_code_to
          ? { dept_code: existingData.dept_code_to, dept_name: existingData.dept_name_to ?? existingData.dept_code_to }
          : null,
      );
      setSectionTo(
        existingData.section_code_to
          ? {
              section_code: existingData.section_code_to,
              section_name: existingData.section_name_to ?? existingData.section_code_to,
            }
          : null,
      );
      setDesignationTo(
        existingData.desg_code_to
          ? { desg_code: existingData.desg_code_to, desg_name: existingData.desg_name_to ?? existingData.desg_code_to }
          : null,
      );
    }
  }, [isEdit, readonly, existingData, companyCode]);

  // ── From-side cascading resets — only relevant while filtering (add
  // mode, no employee picked yet). Picking a parent clears the children. ──
  useEffect(() => {
    if (isEdit || readonly || employee) return;
    setDepartment(null);
    setSection(null);
  }, [division, isEdit, readonly, employee]);

  useEffect(() => {
    if (isEdit || readonly || employee) return;
    setSection(null);
  }, [department, isEdit, readonly, employee]);

  // ── Lookup loader for a single employee's full org placement + designation.
  // Fired the moment an employee is picked directly, so the From-side text
  // fields fill in with real data instead of staying blank. ────────────────
  const loadEmployeeDetail = useCallback(
    (employeeId: string) =>
      getDynamicLookup(
        buildParams("EDUCATION_QUALIFICATION_EMP_TRANSFER_EMP_DETAIL", loginid, companyCode, employeeId),
      ),
    [loginid, companyCode],
  );

  useEffect(() => {
    if (!employee?.employee_id){
    if (isEdit || readonly) return; // edit/view already has everything from existingData
    // Employee cleared — go back to filter mode, blank the snapshot.
      set("div_code", "");
      set("div_name", "");
      set("dept_code", "");
      set("dept_name", "");
      set("section_code", "");
      set("section_name", "");
      set("desg_code", "");
      set("employee_name","");
      set("desg_name", "");
      return;
    }

    let cancelled = false;
    setLoadingEmpDetail(true);

    loadEmployeeDetail(employee.employee_id)
      .then((res) => {
        if (cancelled) return;
        const row = (Array.isArray(res) ? res[0] : null) as Record<string, unknown> | null;

if (row) {
  const employeeName = String(
    row.employee_name ??
    row.rpt_name ??
    employee.employee_name ??
    ""
  );

  setEmployee({
    employee_id: employee.employee_id,
    employee_name: employeeName,
  });

  set("employee_name", employeeName);

  set("div_code", String(row.div_code ?? ""));
  set("div_name", String(row.div_name ?? ""));
  set("dept_code", String(row.dept_code ?? ""));
  set("dept_name", String(row.dept_name ?? ""));
  set("section_code", String(row.section_code ?? ""));
  set("section_name", String(row.section_name ?? ""));
  set("desg_code", String(row.desg_code ?? ""));
  set("desg_name", String(row.desg_name ?? ""));
}
      })
      .finally(() => {
        if (!cancelled) setLoadingEmpDetail(false);
      });

    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [employee?.employee_id, loadEmployeeDetail]);

  // ── To-side cascading resets — unchanged ────────────────────────────────
  useEffect(() => {
    if (isEdit || readonly) return;
    setDepartmentTo(null);
    setSectionTo(null);
  }, [divisionTo, isEdit, readonly]);

  useEffect(() => {
    if (isEdit || readonly) return;
    setSectionTo(null);
  }, [departmentTo, isEdit, readonly]);

  useEffect(() => {
    set("div_code_to", divisionTo?.div_code ?? "");
    set("div_name_to", divisionTo?.div_name ?? "");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [divisionTo]);

  useEffect(() => {
    set("dept_code_to", departmentTo?.dept_code ?? "");
    set("dept_name_to", departmentTo?.dept_name ?? "");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [departmentTo]);

  useEffect(() => {
    set("section_code_to", sectionTo?.section_code ?? "");
    set("section_name_to", sectionTo?.section_name ?? "");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sectionTo]);

  useEffect(() => {
    set("desg_code_to", designationTo?.desg_code ?? "");
    set("desg_name_to", designationTo?.desg_name ?? "");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [designationTo]);

  // ── Lookup loaders — From-side filters (division/department/section) and
  // the employee list itself, all reusing the language-skills parameters. ──

  const loadDivisions = useCallback(
    () => getDynamicLookup(buildParams("EDUCATION_QUALIFICATION_LANG_DIVISION_LIST", loginid, companyCode)),
    [loginid, companyCode],
  );

  const loadDepartments = useCallback(
    () =>
      getDynamicLookup(
        buildParams(
          "EDUCATION_QUALIFICATION_DEPARTMENT_DEPTCODE",
          loginid,
          companyCode,
          division?.div_code ?? "",
        ),
      ),
    [loginid, companyCode, division?.div_code],
  );

  const loadSections = useCallback(
    () =>
      getDynamicLookup(
        buildParams(
          "EDUCATION_QUALIFICATION_MS_HR_SECTION",
          loginid,
          companyCode,
          division?.div_code ?? "",
          department?.dept_code ?? "",
        ),
      ),
    [loginid, companyCode, division?.div_code, department?.dept_code],
  );

  const loadEmployees = useCallback(
    () =>
      getDynamicLookup(
        buildParams(
          "EDUCATION_QUALIFICATION_HR_EMPLOYEE_LIST_WITH_MANAGER",
          loginid,
          companyCode,
          division?.div_code ?? "",
          department?.dept_code ?? "",
          section?.section_code ?? "",
        ),
      ),
    [loginid, companyCode, division?.div_code, department?.dept_code, section?.section_code],
  );

  // ── To-side lookup loaders — company-scoped only, unchanged ────────────
  const loadDivisionsTo = useCallback(
    () => getDynamicLookup(buildParams("EDUCATION_QUALIFICATION_LANG_DIVISION_LIST", loginid, companyCode)),
    [loginid, companyCode],
  );

  const loadDepartmentsTo = useCallback(
    () =>
      getDynamicLookup(
        buildParams(
          "EDUCATION_QUALIFICATION_DEPARTMENT_DEPTCODE",
          loginid,
          companyCode,
          divisionTo?.div_code ?? "",
        ),
      ),
    [loginid, companyCode, divisionTo?.div_code],
  );

  const loadSectionsTo = useCallback(
    () =>
      getDynamicLookup(
        buildParams(
          "EDUCATION_QUALIFICATION_MS_HR_SECTION",
          loginid,
          companyCode,
          divisionTo?.div_code ?? "",
          departmentTo?.dept_code ?? "",
        ),
      ),
    [loginid, companyCode, divisionTo?.div_code, departmentTo?.dept_code],
  );

  const loadDesignationsTo = useCallback(
    () => getDynamicLookup(buildParams("EDUCATION_QUALIFICATION_DESIGNATION_LIST", loginid, companyCode)),
    [loginid, companyCode],
  );

  // ── Validation — Employee stays mandatory regardless of how it was picked ─
  const validate = (): boolean => {
    const next: Partial<Record<keyof TEmployeeTransfer, string>> = {};
    if (!form.employee_id) next.employee_id = "Employee is required";
    if (!form.div_code_to) next.div_code_to = "Division to is required";
    if (!form.dept_code_to) next.dept_code_to = "Department to is required";
    if (!form.section_code_to) next.section_code_to = "Section to is required";
    setErrors(next);
    return Object.keys(next).length === 0;
  };

  // ── Save — parameter "MST_HR_EMP_TRANSFER" ──────────────────────────────
  // Slot layout matches PROC_BUILD_DYNAMIC_INS_UPD_MST_HR exactly:
  //   val1s1  = COMPANY_CODE
  //   val1s2  = DOC_TYPE
  //   val1n1  = DOC_NO (edit only; omit/undefined on insert — auto-generated)
  //   val1s3  = DIV_CODE       (from)
  //   val1s4  = DEPT_CODE      (from)
  //   val1s5  = SECTION_CODE   (from)
  //   val1s6  = EMPLOYEE_ID
  //   val1s7  = DIV_CODE_TO
  //   val1s8  = DEPT_CODE_TO
  //   val1s9  = SECTION_CODE_TO
  //   val1s10 = REMARKS
  //   wval1s1 = APPROVED — no UI control anymore, always sent as 'N'
  //   wval1s2 = DESG_CODE
  //   wval1s3 = DESG_CODE_TO
  const handleSave = async () => {
    if (!validate()) return;
    setSaving(true);
    setApiError("");
    try {
      const docNo =
        isEdit && form.doc_no !== "" && form.doc_no != null ? Number(form.doc_no) : undefined;

      await executeDynamicMutation({
        parameter: "MST_HR_EMP_TRANSFER",
        loginid,
        val1s1: companyCode,
        val1s2: form.doc_type ?? "ETR",
        val1n1: docNo,
        val1s3: form.div_code || "",
        val1s4: form.dept_code || "",
        val1s5: form.section_code || "",
        val1s6: form.employee_id || "",
        val1s7: form.div_code_to || "",
        val1s8: form.dept_code_to || "",
        val1s9: form.section_code_to || "",
        val1s10: form.remarks || "",
        wval1s1: "N",
        wval1s2: form.desg_code || "",
        wval1s3: form.desg_code_to || "",
      });
      onClose(true);
    } catch (error) {
      setApiError(error instanceof Error ? error.message : "Unable to save employee transfer record");
    } finally {
      setSaving(false);
    }
  };

  const handleSubmitClick = () => {
    if (!validate()) return;
    setConfirmSubmitOpen(true);
  };
  const confirmSubmit = async () => {
    setConfirmSubmitOpen(false);
    await handleSave();
  };

  const topGridStyle: CSSProperties = {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    columnGap: "1rem",
    rowGap: "0.75rem",
    minWidth: 0,
  };

  return (
    <div className="grid gap-y-4" style={{ overflowX: "hidden", minWidth: 0 }}>
      {apiError && <div className="alert error">{apiError}</div>}

      {/* ── Current placement — dropdown filters until an employee is
          picked, then read-only text snapshot of that employee's record ── */}
      <div className="min-w-0" style={topGridStyle}>
        {showOrgAsText ? (
          <>
            <label className="field min-w-0">
              <span>Division</span>
              <Input
                type="text"
                disabled
                readOnly
                value={loadingEmpDetail ? "Loading..." : formatCodeName(form.div_code, form.div_name)}
              />
            </label>
            <label className="field min-w-0">
              <span>Department</span>
              <Input
                type="text"
                disabled
                readOnly
                value={loadingEmpDetail ? "Loading..." : formatCodeName(form.dept_code, form.dept_name)}
              />
            </label>
            <label className="field min-w-0">
              <span>Section</span>
              <Input
                type="text"
                disabled
                readOnly
                value={loadingEmpDetail ? "Loading..." : formatCodeName(form.section_code, form.section_name)}
              />
            </label>
          </>
        ) : (
          <>
            <label className="field min-w-0">
              <span>Division</span>
              <LookupField
                compact
                label="Division"
                value={division?.div_code ?? ""}
                displayValue={division ? `${division.div_code} - ${division.div_name}` : ""}
                columns={[
                  { field: "div_code", header: "Code" },
                  { field: "div_name", header: "Division" },
                ]}
                valueField="div_code"
                displayFields={["div_code", "div_name"]}
                loadOptions={loadDivisions}
                onChange={(_, row) =>
                  setDivision(
                    row ? { div_code: String(row.div_code ?? ""), div_name: String(row.div_name ?? "") } : null,
                  )
                }
              />
            </label>
            <label className="field min-w-0">
              <span>Department</span>
              <LookupField
                compact
                label="Department"
                value={department?.dept_code ?? ""}
                displayValue={department ? `${department.dept_code} - ${department.dept_name}` : ""}
                columns={[
                  { field: "dept_code", header: "Code" },
                  { field: "dept_name", header: "Department" },
                ]}
                valueField="dept_code"
                displayFields={["dept_code", "dept_name"]}
                loadOptions={loadDepartments}
                onChange={(_, row) =>
                  setDepartment(
                    row ? { dept_code: String(row.dept_code ?? ""), dept_name: String(row.dept_name ?? "") } : null,
                  )
                }
              />
            </label>
            <label className="field min-w-0">
              <span>Section</span>
              <LookupField
                compact
                label="Section"
                value={section?.section_code ?? ""}
                displayValue={section ? `${section.section_code} - ${section.section_name}` : ""}
                columns={[
                  { field: "section_code", header: "Code" },
                  { field: "section_name", header: "Section" },
                ]}
                valueField="section_code"
                displayFields={["section_code", "section_name"]}
                loadOptions={loadSections}
                onChange={(_, row) =>
                  setSection(
                    row
                      ? {
                          section_code: String(row.section_code ?? ""),
                          section_name: String(row.section_name ?? ""),
                        }
                      : null,
                  )
                }
              />
            </label>
          </>
        )}

        <label className="field min-w-0">
          <span>
            Employee <strong className="text-destructive">*</strong>
          </span>
          <LookupField
            compact
            label="Employee"
            disabled={readonly || isEdit}
            value={employee?.employee_id ?? ""}
            displayValue={employee ? `${employee.employee_id} - ${employee.employee_name}` : ""}
            columns={[
              { field: "employee_id", header: "ID" },
              { field: "employee_name", header: "Employee" },
            ]}
            valueField="employee_id"
            displayFields={["employee_id", "employee_name"]}
            loadOptions={loadEmployees}
            onChange={(_, row) => {
              const picked = row
                ? {
                    employee_id: String(row.employee_id ?? ""),
                    employee_name: String(row.employee_name ?? row.rpt_name ?? ""),
                  }
                : null;
              setEmployee(picked);
              // Write straight onto form state so Transfer-to's
              // `!form.employee_id` gate unlocks immediately, without
              // waiting on the async employee-detail fetch (that fetch
              // only fills in div/dept/section/designation, below).
              set("employee_id", picked?.employee_id ?? "");
              set("employee_name", picked?.employee_name ?? "");
            }}
          />
          {errors.employee_id && (
            <span className="text-destructive text-xs mt-0.5">{errors.employee_id}</span>
          )}
        </label>
      </div>

      <div className="min-w-0" style={topGridStyle}>
        <label className="field min-w-0">
          <span>Date</span>
          <Input
            type="date"
            disabled={readonly}
            value={String(form.user_dt ?? "").slice(0, 10)}
            onChange={(e) => set("user_dt", e.target.value)}
          />
        </label>
        <label className="field min-w-0">
          <span>Designation</span>
          <Input
            type="text"
            disabled
            readOnly
            value={loadingEmpDetail ? "Loading..." : formatCodeName(form.desg_code, form.desg_name)}
          />
        </label>
      </div>

      <hr className="border-border" />

      {/* ── Transfer to — unchanged: cascading Division to / Department to /
          Section to, plus optional Designation to ─────────────────────── */}
      <div>
        <h3 className="m-0 mb-2 text-sm font-semibold">Transfer to</h3>
        <div className="min-w-0" style={topGridStyle}>
          <label className="field min-w-0">
            <span>
              Division to <strong className="text-destructive">*</strong>
            </span>
            <LookupField
              compact
              label="Division to"
              disabled={readonly}
              value={divisionTo?.div_code ?? ""}
              displayValue={divisionTo ? `${divisionTo.div_code} - ${divisionTo.div_name}` : ""}
              columns={[
                { field: "div_code", header: "Code" },
                { field: "div_name", header: "Division" },
              ]}
              valueField="div_code"
              displayFields={["div_code", "div_name"]}
              loadOptions={loadDivisionsTo}
              onChange={(_, row) =>
                setDivisionTo(
                  row ? { div_code: String(row.div_code ?? ""), div_name: String(row.div_name ?? "") } : null,
                )
              }
            />
            {errors.div_code_to && (
              <span className="text-destructive text-xs mt-0.5">{errors.div_code_to}</span>
            )}
          </label>

          <label className="field min-w-0">
            <span>
              Department to <strong className="text-destructive">*</strong>
            </span>
            <LookupField
              compact
              label="Department to"
              disabled={readonly}
              value={departmentTo?.dept_code ?? ""}
              displayValue={departmentTo ? `${departmentTo.dept_code} - ${departmentTo.dept_name}` : ""}
              columns={[
                { field: "dept_code", header: "Code" },
                { field: "dept_name", header: "Department" },
              ]}
              valueField="dept_code"
              displayFields={["dept_code", "dept_name"]}
              loadOptions={loadDepartmentsTo}
              onChange={(_, row) =>
                setDepartmentTo(
                  row ? { dept_code: String(row.dept_code ?? ""), dept_name: String(row.dept_name ?? "") } : null,
                )
              }
            />
            {errors.dept_code_to && (
              <span className="text-destructive text-xs mt-0.5">{errors.dept_code_to}</span>
            )}
          </label>

          <label className="field min-w-0">
            <span>
              Section to <strong className="text-destructive">*</strong>
            </span>
            <LookupField
              compact
              label="Section to"
              disabled={readonly}
              value={sectionTo?.section_code ?? ""}
              displayValue={sectionTo ? `${sectionTo.section_code} - ${sectionTo.section_name}` : ""}
              columns={[
                { field: "section_code", header: "Code" },
                { field: "section_name", header: "Section" },
              ]}
              valueField="section_code"
              displayFields={["section_code", "section_name"]}
              loadOptions={loadSectionsTo}
              onChange={(_, row) =>
                setSectionTo(
                  row
                    ? {
                        section_code: String(row.section_code ?? ""),
                        section_name: String(row.section_name ?? ""),
                      }
                    : null,
                )
              }
            />
            {errors.section_code_to && (
              <span className="text-destructive text-xs mt-0.5">{errors.section_code_to}</span>
            )}
          </label>

          <label className="field min-w-0">
            <span>Designation to</span>
            <LookupField
              compact
              label="Designation to"
              disabled={readonly}
              value={designationTo?.desg_code ?? ""}
              displayValue={designationTo ? `${designationTo.desg_code} - ${designationTo.desg_name}` : ""}
              columns={[
                { field: "desg_code", header: "Code" },
                { field: "desg_name", header: "Designation" },
              ]}
              valueField="desg_code"
              displayFields={["desg_code", "desg_name"]}
              loadOptions={loadDesignationsTo}
              onChange={(_, row) =>
                setDesignationTo(
                  row ? { desg_code: String(row.desg_code ?? ""), desg_name: String(row.desg_name ?? "") } : null,
                )
              }
            />
          </label>
        </div>
      </div>

      <label className="field min-w-0">
        <span>Remarks</span>
        <Input
          type="text"
          disabled={readonly}
          value={form.remarks ?? ""}
          onChange={(e) => set("remarks", e.target.value)}
        />
      </label>

      {/* ── Actions ──────────────────────────────────────────────────────── */}
      <div className="flex flex-wrap justify-end gap-2 border-t pt-3">
        <Button variant="outline" onClick={() => onClose(false)}>
          <X size={15} /> {readonly ? "Close" : "Cancel"}
        </Button>
        {!readonly && (
          <>
            <Button variant="outline" disabled={saving} onClick={handleSave}>
              <Save size={15} /> {saving ? "Saving..." : "Save as Draft"}
            </Button>
            <Button disabled={saving} onClick={handleSubmitClick}>
              <Send size={15} /> Submit
            </Button>
          </>
        )}
      </div>

      {/* ── Submit confirmation ──────────────────────────────────────────── */}
      <Dialog
        open={confirmSubmitOpen}
        title="Submit"
        description="Are you sure you want to Submit?"
        compact
        onClose={() => setConfirmSubmitOpen(false)}
        footer={
          <>
            <Button variant="outline" onClick={() => setConfirmSubmitOpen(false)}>
              No
            </Button>
            <Button onClick={confirmSubmit} disabled={saving}>
              Yes
            </Button>
          </>
        }
      >
        <p className="text-sm text-muted-foreground">
          This will submit the transfer for <strong>{form.employee_name || "(selected employee)"}</strong>.
        </p>
      </Dialog>
    </div>
  );
}