import { FormikProps } from 'formik';
import { TPayUnitFormValues } from './AddPayUnitsForm';
import { useEffect, useState } from 'react';
import { useAuth } from '../../../state/AuthContext';
import { getDynamicLookup } from '../../../api/lookups';
import { Input } from '../../../components/ui/Input';
import { Select } from '../../../components/ui/Select';

type TProps = {
  formik: FormikProps<TPayUnitFormValues>;
  isEdit: boolean;
  disabled?: boolean;
};

const PAY_COMP_TYPE_OPTIONS = [
  { label: 'Fixed', value: 'F' },
  { label: 'Variable', value: 'V' }
];
const YES_NO_OPTIONS = ['Y', 'N'];


type TCodeOption = { value_code: string; value_desc: string };


const useCodeOptions = (parameter: string) => {
  const { user } = useAuth();
  const [options, setOptions] = useState<TCodeOption[]>([]);

  useEffect(() => {
    const fetchOptions = async () => {
      try {
        const response = await getDynamicLookup({
          parameter,
          loginid: user?.loginid ?? '',
          code1: user?.company_code ?? ''
        });
        if (Array.isArray(response)) {
          setOptions(
            response.map((row: any) => ({
              value_code: row.VALUE_CODE ?? row.value_code ?? '',
              value_desc: row.VALUE_DESC ?? row.value_desc ?? ''
            }))
          );
        }
      } catch (e) {
        console.error(e);
      }
    };
    if (user?.company_code) fetchOptions();
  }, [user?.company_code, parameter]);

  return options;
};

// ── Small helper: label + error/helper text under a field ──────────────────
function FieldHint({ error, helper }: { error?: string; helper?: string }) {
  if (error) return <p className="mt-1 text-xs text-destructive">{error}</p>;
  if (helper) return <p className="mt-1 text-xs text-muted-foreground">{helper}</p>;
  return null;
}

// ===================== MAIN COMPONENT =====================
const PayUnitHeaderForm = ({ formik, disabled = false }: TProps) => {
  const { values, errors, touched, handleChange, handleBlur } = formik;

  const earnDedOptions = useCodeOptions('PAY_COMPONENT_EAR_DED_CodeValue');
  const payCompDependentOptions = useCodeOptions('PAY_COMPONENT_DEPENDENT_CodeValue');
  const periodicityOptions = useCodeOptions('PAY_COMPONENT_PERIODICITY_CodeValue');
  const attendDepOptions = useCodeOptions('PAY_COMPONENT_ATTENDANCE_DEP_CodeValue');
  const taxableOptions = useCodeOptions('PAY_COMPONENT_TAXABLE_CodeValue');
  const payFlagOptions = useCodeOptions('PAY_COMPONENT_PAY_FLAG_CodeValue');
  const roundOffOptions = useCodeOptions('PAY_COMPONENT_ROUND_OFF_CodeValue');
  const statusOptions = useCodeOptions('PAY_COMPONENT_STATUS_CodeValue');

  return (
    <div className="col-span-12 grid gap-3">
      {/* ===================== PAY UNIT INFO ===================== */}
      <div className="flex flex-col gap-2 rounded-lg border border-[#d0dcf5] bg-[#f0f5ff] p-2">
        <p className="m-0 text-[0.68rem] font-bold uppercase tracking-wide text-[#082A89]">PayUnit Info</p>

        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 md:grid-cols-4">
          {/* Division */}
          <label className="field">
            <span>Division Code</span>
            <Input
              disabled
              readOnly
              className="bg-white"
              value={values.div_code && values.div_name ? `${values.div_code} - ${values.div_name}` : values.div_code || ''}
            />
            <FieldHint helper="Auto-filled from division selection" />
          </label>

          {/* PAY_COMP_ID — auto-generated by DB trigger, read-only */}
          <label className="field">
            <span>Pay Component ID</span>
            <Input
              className="bg-white"
              name="pay_comp_id"
              value={values.pay_comp_id}
              placeholder="Auto-generated"
              disabled
              readOnly
            />
            <FieldHint helper="Auto-generated on save" />
          </label>

          {/* PAY_COMP_DESC */}
          <label className="field">
            <span>Pay Unit name</span>
            <Input
              className="bg-white"
              name="pay_comp_desc"
              value={values.pay_comp_desc}
              onChange={handleChange}
              onBlur={handleBlur}
              disabled={disabled}
            />
            <FieldHint error={touched.pay_comp_desc && errors.pay_comp_desc ? String(errors.pay_comp_desc) : undefined} />
          </label>

          {/* PAY_COMP_SHORT_DESC */}
          <label className="field">
            <span>Short Description</span>
            <Input
              className="bg-white"
              name="pay_comp_short_desc"
              value={values.pay_comp_short_desc}
              onChange={handleChange}
              onBlur={handleBlur}
              disabled={disabled}
            />
            <FieldHint
              error={touched.pay_comp_short_desc && errors.pay_comp_short_desc ? String(errors.pay_comp_short_desc) : undefined}
            />
          </label>
        </div>
      </div>

      {/* ===================== PAYROLL PARAMETER ===================== */}
      <div className="flex flex-col gap-2 rounded-lg border border-[#d0dcf5] bg-[#f0f5ff] p-2">
        <p className="m-0 text-[0.68rem] font-bold uppercase tracking-wide text-[#082A89]">Payroll Parameter</p>

        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 md:grid-cols-4">
          {/* PAY_COMP_TYPE */}
          <label className="field">
            <span>Pay Unit Type</span>
            <Select
              className="bg-white"
              name="pay_comp_type"
              value={values.pay_comp_type}
              onChange={handleChange}
              onBlur={handleBlur}
              disabled={disabled}
            >
              <option value="">Select</option>
              {PAY_COMP_TYPE_OPTIONS.map((opt) => (
                <option key={opt.value} value={opt.value}>
                  {opt.label}
                </option>
              ))}
            </Select>
            <FieldHint error={touched.pay_comp_type && errors.pay_comp_type ? String(errors.pay_comp_type) : undefined} />
          </label>

          {/* PAY_COMP_EARN_DED — dynamic dropdown */}
          <label className="field">
            <span>Earning / Deduction</span>
            <Select
              className="bg-white"
              name="pay_comp_earn_ded"
              value={values.pay_comp_earn_ded}
              onChange={handleChange}
              onBlur={handleBlur}
              disabled={disabled}
            >
              <option value="">Select</option>
              {earnDedOptions.map((opt) => (
                <option key={opt.value_code} value={opt.value_code}>
                  {opt.value_code} - {opt.value_desc}
                </option>
              ))}
            </Select>
            <FieldHint
              error={touched.pay_comp_earn_ded && errors.pay_comp_earn_ded ? String(errors.pay_comp_earn_ded) : undefined}
            />
          </label>

          <label className="field">
            <span>Pay Component Dependent</span>
            <Select
              className="bg-white"
              name="pay_comp_dependent"
              value={values.pay_comp_dependent || ''}
              onChange={handleChange}
              onBlur={handleBlur}
              disabled={disabled}
            >
              <option value="">Select</option>
              {payCompDependentOptions.map((opt) => (
                <option key={opt.value_code} value={opt.value_code}>
                  {opt.value_code} - {opt.value_desc}
                </option>
              ))}
            </Select>
            <FieldHint
              error={touched.pay_comp_dependent && errors.pay_comp_dependent ? String(errors.pay_comp_dependent) : undefined}
            />
          </label>

          <label className="field">
            <span>Periodicity</span>
            <Select
              className="bg-white"
              name="periodicity"
              value={values.periodicity || ''}
              onChange={handleChange}
              onBlur={handleBlur}
              disabled={disabled}
            >
              <option value="">Select</option>
              {periodicityOptions.map((opt) => (
                <option key={opt.value_code} value={opt.value_code}>
                  {opt.value_code} - {opt.value_desc}
                </option>
              ))}
            </Select>
            <FieldHint error={touched.periodicity && errors.periodicity ? String(errors.periodicity) : undefined} />
          </label>

          <label className="field">
            <span>Attendance Dependency</span>
            <Select
              className="bg-white"
              name="attendance_dependency"
              value={values.attendance_dependency || ''}
              onChange={(e) => {
                const code = e.target.value;
                handleChange(e);
                const selected = attendDepOptions.find((opt) => opt.value_code === code);
                formik.setFieldValue('attendance_dependency_desc', selected?.value_desc ?? '');
              }}
              onBlur={handleBlur}
              disabled={disabled}
            >
              <option value="">Select</option>
              {attendDepOptions.map((opt) => (
                <option key={opt.value_code} value={opt.value_code}>
                  {opt.value_code} - {opt.value_desc}
                </option>
              ))}
            </Select>
            <FieldHint
              error={touched.attendance_dependency && errors.attendance_dependency ? String(errors.attendance_dependency) : undefined}
            />
          </label>

          <label className="field">
            <span>Taxable</span>
            <Select
              className="bg-white"
              name="taxable"
              value={values.taxable || ''}
              onChange={(e) => {
                const code = e.target.value;
                handleChange(e);
                const selected = taxableOptions.find((opt) => opt.value_code === code);
                formik.setFieldValue('taxable_desc', selected?.value_desc ?? '');
              }}
              onBlur={handleBlur}
              disabled={disabled}
            >
              <option value="">Select</option>
              {taxableOptions.map((opt) => (
                <option key={opt.value_code} value={opt.value_code}>
                  {opt.value_code} - {opt.value_desc}
                </option>
              ))}
            </Select>
            <FieldHint error={touched.taxable && errors.taxable ? String(errors.taxable) : undefined} />
          </label>

          {/* PAY UNIT CATEGORY */}
          <label className="field">
            <span>Pay Unit Category</span>
            <Select
              className="bg-white"
              name="pay_flag"
              value={values.pay_flag || ''}
              onChange={(e) => {
                const code = e.target.value;
                handleChange(e);
                const selected = payFlagOptions.find((opt) => opt.value_code === code);
                formik.setFieldValue('pay_flag_desc', selected?.value_desc ?? '');
              }}
              onBlur={handleBlur}
              disabled={disabled}
            >
              <option value="">Select </option>
              {payFlagOptions.map((opt) => (
                <option key={opt.value_code} value={opt.value_code}>
                  {opt.value_code} - {opt.value_desc}
                </option>
              ))}
            </Select>
            <FieldHint error={touched.pay_flag && errors.pay_flag ? String(errors.pay_flag) : undefined} />
          </label>

          <label className="field">
            <span>Round Off To</span>
            <Select
              className="bg-white"
              name="round_off_to"
              value={values.round_off_to || ''}
              onChange={(e) => {
                const code = e.target.value;
                handleChange(e);
                const selected = roundOffOptions.find((opt) => opt.value_code === code);
                formik.setFieldValue('round_off_to_desc', selected?.value_desc ?? '');
              }}
              onBlur={handleBlur}
              disabled={disabled}
            >
              <option value="">Select</option>
              {roundOffOptions.map((opt) => (
                <option key={opt.value_code} value={opt.value_code}>
                  {opt.value_code} - {opt.value_desc}
                </option>
              ))}
            </Select>
            <FieldHint error={touched.round_off_to && errors.round_off_to ? String(errors.round_off_to) : undefined} />
          </label>

          {/* LEAVE_PAID */}
          <label className="field">
            <span>Leave Paid</span>
            <Select
              className="bg-white"
              name="leave_paid"
              value={values.leave_paid}
              onChange={handleChange}
              onBlur={handleBlur}
              disabled={disabled}
            >
              {YES_NO_OPTIONS.map((opt) => (
                <option key={opt} value={opt}>
                  {opt === 'Y' ? 'Yes' : 'No'}
                </option>
              ))}
            </Select>
            <FieldHint error={touched.leave_paid && errors.leave_paid ? String(errors.leave_paid) : undefined} />
          </label>

          {/* SALARY_LINK */}
          <label className="field">
            <span>Salary Link</span>
            <Select
              className="bg-white"
              name="salary_link"
              value={values.salary_link}
              onChange={handleChange}
              onBlur={handleBlur}
              disabled={disabled}
            >
              {YES_NO_OPTIONS.map((opt) => (
                <option key={opt} value={opt}>
                  {opt === 'Y' ? 'Yes' : 'No'}
                </option>
              ))}
            </Select>
            <FieldHint error={touched.salary_link && errors.salary_link ? String(errors.salary_link) : undefined} />
          </label>

          <label className="field">
            <span>Status</span>
            <Select
              className="bg-white"
              name="status"
              value={values.status || ''}
              onChange={(e) => {
                const code = e.target.value;
                handleChange(e);
                const selected = statusOptions.find((opt) => opt.value_code === code);
                formik.setFieldValue('status_desc', selected?.value_desc ?? '');
              }}
              onBlur={handleBlur}
              disabled={disabled}
            >
              <option value="">Select</option>
              {statusOptions.map((opt) => (
                <option key={opt.value_code} value={opt.value_code}>
                  {opt.value_code} - {opt.value_desc}
                </option>
              ))}
            </Select>
            <FieldHint error={touched.status && errors.status ? String(errors.status) : undefined} />
          </label>

          {/* REMARKS — full width */}
          <label className="field col-span-1 sm:col-span-1 md:col-span-4">
            <span>Remarks</span>
            <textarea
              className="w-full rounded-md border bg-white px-2 py-1 text-sm"
              rows={2}
              name="remarks"
              value={values.remarks}
              onChange={handleChange}
              onBlur={handleBlur}
              disabled={disabled}
            />
            <FieldHint error={touched.remarks && errors.remarks ? String(errors.remarks) : undefined} />
          </label>
        </div>
      </div>
    </div>
  );
};

export default PayUnitHeaderForm;