// src/pages/hr/payunits/PayUnitHeaderForm.tsx
//
// Pay Unit header — new UI: two Freight SectionPanels (Pay Unit Info /
// Payroll Parameter), shared Field wrapper, and one reusable CodeSelectField
// replacing the eight copy-pasted code-list <Select> blocks.

import { FormikProps } from 'formik';
import { IdCard, SlidersHorizontal } from 'lucide-react';
import type { TPayUnitFormValues } from './AddPayUnitsForm';
import { Field, SectionPanel } from '../../../components/ui/Freightpanel';
import { Input } from '../../../components/ui/Input';
import { Select } from '../../../components/ui/Select';
import { useCodeOptions } from '../../../components/ui/Usecodeoptions';

type TProps = {
  formik: FormikProps<TPayUnitFormValues>;
  isEdit: boolean;
  disabled?: boolean;
};

const PAY_COMP_TYPE_OPTIONS = [
  { label: 'Fixed', value: 'F' },
  { label: 'Variable', value: 'V' }
];

const YES_NO_OPTIONS = [
  { label: 'Yes', value: 'Y' },
  { label: 'No', value: 'N' }
];

// ── Code-list select: loads VALUE_CODE / VALUE_DESC options for `parameter`,
//    and (optionally) writes the selected description into `descField`.
function CodeSelectField({
  formik,
  name,
  label,
  parameter,
  descField,
  disabled
}: {
  formik: FormikProps<TPayUnitFormValues>;
  name: keyof TPayUnitFormValues;
  label: string;
  parameter: string;
  descField?: keyof TPayUnitFormValues;
  disabled?: boolean;
}) {
  const options = useCodeOptions(parameter);
  const { values, errors, touched, handleChange, handleBlur } = formik;
  const fieldName = String(name);
  const error =
    (touched as Record<string, unknown>)[fieldName] && (errors as Record<string, unknown>)[fieldName]
      ? String((errors as Record<string, unknown>)[fieldName])
      : undefined;

  return (
    <Field label={label} error={error}>
      <Select
        name={fieldName}
        value={String(values[name] ?? '')}
        onChange={(e) => {
          handleChange(e);
          if (descField) {
            const selected = options.find((opt) => opt.value_code === e.target.value);
            void formik.setFieldValue(String(descField), selected?.value_desc ?? '');
          }
        }}
        onBlur={handleBlur}
        disabled={disabled}
      >
        <option value="">Select</option>
        {options.map((opt) => (
          <option key={opt.value_code} value={opt.value_code}>
            {opt.value_code} - {opt.value_desc}
          </option>
        ))}
      </Select>
    </Field>
  );
}

// ===================== MAIN COMPONENT =====================
const PayUnitHeaderForm = ({ formik, disabled = false }: TProps) => {
  const { values, errors, touched, handleChange, handleBlur } = formik;

  const fieldError = (name: keyof TPayUnitFormValues) =>
    touched[name] && errors[name] ? String(errors[name]) : undefined;

  return (
    <>
      {/* ===================== PAY UNIT INFO ===================== */}
      <SectionPanel title="Pay Unit Info" icon={IdCard}>
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 md:grid-cols-4">
          {/* Division — auto-filled from the picker */}
          <Field label="Division Code" helperText="Auto-filled from division selection">
            <Input
              disabled
              readOnly
              value={
                values.div_code && values.div_name ? `${values.div_code} - ${values.div_name}` : values.div_code || ''
              }
            />
          </Field>

          {/* PAY_COMP_ID — auto-generated by DB trigger, read-only */}
          <Field label="Pay Component ID" helperText="Auto-generated on save">
            <Input name="pay_comp_id" value={values.pay_comp_id} placeholder="Auto-generated" disabled readOnly />
          </Field>

          <Field label="Pay Unit Name" required error={fieldError('pay_comp_desc')}>
            <Input
              name="pay_comp_desc"
              value={values.pay_comp_desc}
              onChange={handleChange}
              onBlur={handleBlur}
              disabled={disabled}
            />
          </Field>

          <Field label="Short Description" error={fieldError('pay_comp_short_desc')}>
            <Input
              name="pay_comp_short_desc"
              value={values.pay_comp_short_desc}
              onChange={handleChange}
              onBlur={handleBlur}
              disabled={disabled}
            />
          </Field>
        </div>
      </SectionPanel>

      {/* ===================== PAYROLL PARAMETER ===================== */}
      <SectionPanel title="Payroll Parameter" icon={SlidersHorizontal}>
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 md:grid-cols-4">
          <Field label="Pay Unit Type" error={fieldError('pay_comp_type')}>
            <Select
              name="pay_comp_type"
              value={values.pay_comp_type}
              onChange={handleChange}
              onBlur={handleBlur}
              disabled={disabled}
            >
              <option value="">Select</option>
              {PAY_COMP_TYPE_OPTIONS.map((opt) => (
                <option key={opt.value} value={opt.value}>
                  {opt.label}
                </option>
              ))}
            </Select>
          </Field>

          <CodeSelectField
            formik={formik}
            disabled={disabled}
            name="pay_comp_earn_ded"
            label="Earning / Deduction"
            parameter="PAY_COMPONENT_EAR_DED_CodeValue"
          />

          <CodeSelectField
            formik={formik}
            disabled={disabled}
            name="pay_comp_dependent"
            label="Pay Component Dependent"
            parameter="PAY_COMPONENT_DEPENDENT_CodeValue"
          />

          <CodeSelectField
            formik={formik}
            disabled={disabled}
            name="periodicity"
            label="Periodicity"
            parameter="PAY_COMPONENT_PERIODICITY_CodeValue"
          />

          <CodeSelectField
            formik={formik}
            disabled={disabled}
            name="attendance_dependency"
            descField="attendance_dependency_desc"
            label="Attendance Dependency"
            parameter="PAY_COMPONENT_ATTENDANCE_DEP_CodeValue"
          />

          <CodeSelectField
            formik={formik}
            disabled={disabled}
            name="taxable"
            descField="taxable_desc"
            label="Taxable"
            parameter="PAY_COMPONENT_TAXABLE_CodeValue"
          />

          <CodeSelectField
            formik={formik}
            disabled={disabled}
            name="pay_flag"
            descField="pay_flag_desc"
            label="Pay Unit Category"
            parameter="PAY_COMPONENT_PAY_FLAG_CodeValue"
          />

          <CodeSelectField
            formik={formik}
            disabled={disabled}
            name="round_off_to"
            descField="round_off_to_desc"
            label="Round Off To"
            parameter="PAY_COMPONENT_ROUND_OFF_CodeValue"
          />

          <Field label="Leave Paid" error={fieldError('leave_paid')}>
            <Select
              name="leave_paid"
              value={values.leave_paid}
              onChange={handleChange}
              onBlur={handleBlur}
              disabled={disabled}
            >
              {YES_NO_OPTIONS.map((opt) => (
                <option key={opt.value} value={opt.value}>
                  {opt.label}
                </option>
              ))}
            </Select>
          </Field>

          <Field label="Salary Link" error={fieldError('salary_link')}>
            <Select
              name="salary_link"
              value={values.salary_link}
              onChange={handleChange}
              onBlur={handleBlur}
              disabled={disabled}
            >
              {YES_NO_OPTIONS.map((opt) => (
                <option key={opt.value} value={opt.value}>
                  {opt.label}
                </option>
              ))}
            </Select>
          </Field>

          <CodeSelectField
            formik={formik}
            disabled={disabled}
            name="status"
            descField="status_desc"
            label="Status"
            parameter="PAY_COMPONENT_STATUS_CodeValue"
          />

          {/* REMARKS — full width */}
          <Field label="Remarks" error={fieldError('remarks')} className="sm:col-span-2 md:col-span-4">
            <textarea
              className="input"
              rows={2}
              name="remarks"
              value={values.remarks}
              onChange={handleChange}
              onBlur={handleBlur}
              disabled={disabled}
              style={{ resize: 'vertical', fontFamily: 'inherit' }}
            />
          </Field>
        </div>
      </SectionPanel>
    </>
  );
};

export default PayUnitHeaderForm;