import type { WmsSimpleMasterConfig } from "./WmsSimpleMasterPage";

const yesNo = [
  { label: "No", value: "N" },
  { label: "Yes", value: "Y" },
];

const activeInactive = [
  { label: "Active", value: "A" },
  { label: "Inactive", value: "I" },
];

const transportMode = [
  { label: "Sea", value: "S" },
  { label: "Air", value: "A" },
  { label: "Road", value: "R" },
];

export const wmsSimpleMasterConfigs: Record<string, WmsSimpleMasterConfig> = {
  producttype: {
    title: "Product Type Master",
    subtitle: "Maintain product type codes used by product and inbound setup.",
    master: "producttype",
    gmEndpoint: "producttype",
    routeKeys: ["producttype", "product_type", "product-type"],
    keyField: "prodtype_code",
    fields: [
      { name: "prodtype_code", label: "Product Type Code", required: true, disabledOnEdit: true, width: 170 },
      { name: "prodtype_desc", label: "Product Type Description", required: true, width: 280 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.prodtype_code] },
  },
  activitygroup: {
    title: "Activity Group Master",
    subtitle: "Maintain WMS activity groups, validation behavior, accounting links, and reporting group.",
    master: "activitygroup",
    gmEndpoint: "activitygroup",
    routeKeys: ["activitygroup", "activity_group", "activity-group"],
    keyField: "activity_group_code",
    fields: [
      { name: "activity_group_code", label: "Activity Group Code", required: true, disabledOnEdit: true, width: 180 },
      { name: "act_group_name", label: "Activity Group Name", required: true, width: 260 },
      { name: "mandatory_flag", label: "Mandatory", type: "select", options: yesNo, width: 120 },
      { name: "validate_flag", label: "Validate", type: "select", options: yesNo, width: 120 },
      { name: "act_group_type", label: "Group Type", width: 140 },
      { name: "account_code", label: "Account Code", width: 150 },
      { name: "alternate_accode", label: "Alternate Account", width: 160 },
      { name: "exp_account_code", label: "Expense Account", width: 160 },
      { name: "freight_flag", label: "Freight", type: "select", options: yesNo, width: 110 },
      { name: "sw_flag", label: "SW Flag", type: "select", options: yesNo, width: 110 },
      { name: "rpt_group_name", label: "Report Group", width: 180 },
      { name: "sort_order", label: "Sort Order", type: "number", width: 120 },
      { name: "cost_group", label: "Cost Group", width: 140 },
    ],
    defaults: { mandatory_flag: "N", validate_flag: "N", freight_flag: "N", sw_flag: "N" },
    deleteConfig: { mode: "registered", payload: (row) => [row.activity_group_code] },
  },
  activitysubgroup: {
    title: "Activity Sub Group Master",
    subtitle: "Maintain activity sub groups linked with WMS activity groups.",
    master: "activitysubgroup",
    gmEndpoint: "activitysubgroup",
    routeKeys: ["activitysubgroup", "activity_subgroup", "activity-subgroup"],
    keyField: "activity_subgroup_code",
    fields: [
      { name: "activity_subgroup_code", label: "Sub Group Code", required: true, disabledOnEdit: true, width: 170 },
      { name: "act_subgroup_name", label: "Sub Group Name", required: true, width: 260 },
      { name: "act_group_code", label: "Activity Group Code", required: true, width: 180 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.activity_subgroup_code] },
  },
  activitykpi: {
    title: "Activity KPI Master",
    subtitle: "Maintain expected hours by principal, activity, customer, and job type.",
    master: "activitykpi",
    gmEndpoint: "activity-kpi",
    routeKeys: ["activity-kpi", "activitykpi", "activity_kpi"],
    keyField: "act_code",
    fields: [
      { name: "prin_code", label: "Principal Code", required: true, width: 160 },
      { name: "job_type", label: "Job Type", required: true, width: 130 },
      { name: "act_code", label: "Activity Code", required: true, width: 150 },
      { name: "cust_code", label: "Customer Code", required: true, width: 150 },
      { name: "exp_hours", label: "Expected Hours", type: "number", width: 150 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.prin_code] },
  },
  department: {
    title: "Department Master",
    subtitle: "Maintain department code, name, and division link.",
    master: "department",
    gmEndpoint: "department",
    routeKeys: ["department"],
    keyField: "dept_code",
    fields: [
      { name: "dept_code", label: "Department Code", required: true, disabledOnEdit: true, width: 170 },
      { name: "dept_name", label: "Department Name", required: true, width: 260 },
      { name: "div_code", label: "Division Code", width: 150 },
    ],
    deleteConfig: { mode: "rawDelete", payload: (row) => ({ ids: [row.dept_code] }) },
  },
  division: {
    title: "Division Master",
    subtitle: "Maintain division identity, address, contacts, and status.",
    master: "division",
    gmEndpoint: "division",
    routeKeys: ["division"],
    keyField: "div_code",
    fields: [
      { name: "div_code", label: "Division Code", required: true, disabledOnEdit: true, width: 150 },
      { name: "div_name", label: "Division Name", required: true, width: 260 },
      { name: "div_short_name", label: "Short Name", width: 150 },
      { name: "country_code", label: "Country Code", width: 140 },
      { name: "phone", label: "Phone", width: 150 },
      { name: "fax", label: "Fax", width: 140 },
      { name: "email", label: "Email", type: "email", width: 220 },
      { name: "status", label: "Status", type: "select", options: activeInactive, width: 120 },
      { name: "div_address1", label: "Address 1", table: false },
      { name: "div_address2", label: "Address 2", table: false },
      { name: "div_address3", label: "Address 3", table: false },
      { name: "remarks", label: "Remarks", table: false },
    ],
    defaults: { status: "A" },
    deleteConfig: { mode: "rawDelete", payload: (row) => [{ company_code: row.company_code, div_code: row.div_code }] },
  },
  manufacture: {
    title: "Manufacturer Master",
    subtitle: "Maintain manufacturer codes by principal.",
    master: "manufacturer",
    gmEndpoint: "manufacture",
    routeKeys: ["manufacture", "manufacturer"],
    keyField: "manu_code",
    fields: [
      { name: "manu_code", label: "Manufacturer Code", required: true, disabledOnEdit: true, width: 180 },
      { name: "manu_name", label: "Manufacturer Name", required: true, width: 280 },
      { name: "prin_code", label: "Principal Code", width: 160 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [{ manu_code: row.manu_code, prin_code: row.prin_code }] },
  },
  moc2: {
    title: "MOC2 Master",
    subtitle: "Maintain charge codes, charge type, and activity group mapping.",
    master: "moc2",
    gmEndpoint: "moc2",
    routeKeys: ["moc2"],
    keyField: "charge_code",
    fields: [
      { name: "charge_code", label: "Charge Code", required: true, width: 150 },
      { name: "description", label: "Description", required: true, width: 260 },
      { name: "charge_type", label: "Charge Type", required: true, width: 140 },
      { name: "activity_group_code", label: "Activity Group", required: true, width: 170 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [{ charge_code: row.charge_code, charge_type: row.charge_type, company_code: row.company_code }] },
  },
  moc: {
    title: "MOC Master",
    subtitle: "Maintain mode of collection codes and activity group mapping.",
    master: "moc",
    gmEndpoint: "moc",
    routeKeys: ["moc"],
    keyField: "moc_code",
    fields: [
      { name: "moc_code", label: "MOC Code", required: true, disabledOnEdit: true, width: 140 },
      { name: "moc_name", label: "MOC Name", required: true, width: 260 },
      { name: "activity_group_code", label: "Activity Group", width: 170 },
      { name: "description", label: "Description", width: 260 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => ({ moc_code: row.moc_code, company_code: row.company_code }) },
  },
  harmonize: {
    title: "Harmonize Code Master",
    subtitle: "Maintain harmonized commodity and customs reference codes.",
    master: "harmonize",
    gmEndpoint: "harmonize",
    routeKeys: ["harmonize"],
    keyField: "harm_code",
    fields: [
      { name: "harm_code", label: "Harmonize Code", required: true, disabledOnEdit: true, width: 170 },
      { name: "harm_desc", label: "Description", required: true, width: 320 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.harm_code] },
  },
  port: {
    title: "Port Master",
    subtitle: "Maintain port codes by country and transport mode.",
    master: "port",
    gmEndpoint: "port",
    routeKeys: ["port"],
    keyField: "port_code",
    fields: [
      { name: "port_code", label: "Port Code", required: true, disabledOnEdit: true, width: 140 },
      { name: "port_name", label: "Port Name", required: true, width: 260 },
      { name: "country_code", label: "Country Code", width: 150 },
      { name: "trp_mode", label: "Transport Mode", type: "select", options: transportMode, width: 150 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.port_code] },
  },
  partner: {
    title: "Partner Master",
    subtitle: "Maintain broker and partner contact information.",
    master: "partner",
    gmEndpoint: "partner",
    routeKeys: ["partner", "broker"],
    keyField: "broker_code",
    fields: [
      { name: "broker_code", label: "Partner Code", required: true, disabledOnEdit: true, width: 150 },
      { name: "broker_name", label: "Partner Name", required: true, width: 260 },
      { name: "country_code", label: "Country Code", width: 140 },
      { name: "broker_city", label: "City", width: 150 },
      { name: "broker_contact1", label: "Contact", width: 180 },
      { name: "broker_telno1", label: "Telephone", width: 150 },
      { name: "broker_email1", label: "Email", type: "email", width: 220 },
      { name: "broker_addr1", label: "Address 1", table: false },
      { name: "broker_addr2", label: "Address 2", table: false },
      { name: "broker_addr3", label: "Address 3", table: false },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.broker_code] },
  },
  locationtype: {
    title: "Location Type Master",
    subtitle: "Maintain warehouse location dimensions and push level setup.",
    master: "locationtype",
    gmEndpoint: "locationtype",
    routeKeys: ["locationtype", "location_type", "location-type"],
    keyField: "loc_type",
    fields: [
      { name: "loc_type", label: "Location Type", required: true, disabledOnEdit: true, width: 150 },
      { name: "loc_name", label: "Location Name", required: true, width: 240 },
      { name: "loc_cbm", label: "CBM", type: "number", width: 120 },
      { name: "loc_wt", label: "Weight", type: "number", width: 120 },
      { name: "push_level", label: "Push Level", type: "number", width: 130 },
    ],
    deleteConfig: { mode: "disabled", payload: () => null, reason: "Delete endpoint is not registered in the existing backend" },
  },
  salesman: {
    title: "Salesman Master",
    subtitle: "Maintain salesman codes and names.",
    master: "salesman",
    gmEndpoint: "salesman",
    routeKeys: ["salesman"],
    keyField: "salesman_code",
    fields: [
      { name: "salesman_code", label: "Salesman Code", required: true, disabledOnEdit: true, width: 160 },
      { name: "salesman_name", label: "Salesman Name", required: true, width: 280 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.salesman_code] },
  },
  alert: {
    title: "Alert Master",
    subtitle: "Maintain operational alert sequence, module, mode, and instruction text.",
    master: "alert",
    gmEndpoint: "alert",
    routeKeys: ["alert"],
    keyField: "op_code",
    fields: [
      { name: "op_type", label: "Operation Type", required: true, width: 150 },
      { name: "op_code", label: "Operation Code", required: true, width: 160 },
      { name: "op_desc", label: "Description", required: true, width: 260 },
      { name: "op_sequence", label: "Sequence", type: "number", width: 120 },
      { name: "op_module", label: "Module", width: 130 },
      { name: "op_mode", label: "Mode", width: 120 },
      { name: "instruction", label: "Instruction", table: false },
    ],
    saveEndpoint: (form, { editMode, original }) =>
      editMode ? `alert/${original?.op_type || form.op_type}/${original?.op_code || form.op_code}` : "alert",
    deleteConfig: { mode: "registered", payload: (row) => [{ op_type: row.op_type, op_code: row.op_code, company_code: row.company_code }] },
  },
  principal: {
    title: "Principal Master",
    subtitle: "Maintain principal identity, division, country, currency, and primary contact details.",
    master: "principal",
    gmEndpoint: "principal",
    routeKeys: ["principal"],
    keyField: "prin_code",
    fields: [
      { name: "prin_code", label: "Principal Code", required: true, disabledOnEdit: true, width: 160 },
      { name: "prin_name", label: "Principal Name", required: true, width: 280 },
      { name: "div_code", label: "Division Code", width: 140 },
      { name: "country_code", label: "Country Code", width: 140 },
      { name: "curr_code", label: "Currency", width: 130 },
      { name: "prin_city", label: "City", width: 150 },
      { name: "prin_contact1", label: "Contact", width: 180 },
      { name: "prin_telno1", label: "Telephone", width: 150 },
      { name: "prin_email1", label: "Email", type: "email", width: 220 },
      { name: "prin_addr1", label: "Address 1", table: false },
      { name: "prin_addr2", label: "Address 2", table: false },
      { name: "prin_addr3", label: "Address 3", table: false },
    ],
    saveEndpoint: (form, { editMode, original }) => (editMode ? `principal/${original?.prin_code || form.prin_code}` : "principal"),
    deleteConfig: { mode: "disabled", payload: () => null, reason: "Delete endpoint is not registered in the existing backend" },
  },
  customer: {
    title: "Customer Master",
    subtitle: "Maintain customer details by principal with currency, country, and contacts.",
    master: "customer",
    gmEndpoint: "customer",
    routeKeys: ["customer"],
    keyField: "cust_code",
    fields: [
      { name: "prin_code", label: "Principal Code", required: true, width: 150 },
      { name: "cust_code", label: "Customer Code", required: true, disabledOnEdit: true, width: 150 },
      { name: "cust_name", label: "Customer Name", required: true, width: 280 },
      { name: "curr_code", label: "Currency", width: 130 },
      { name: "country_code", label: "Country Code", width: 140 },
      { name: "cust_city", label: "City", width: 150 },
      { name: "cust_contact1", label: "Contact", width: 180 },
      { name: "cust_telno1", label: "Telephone", width: 150 },
      { name: "cust_email1", label: "Email", type: "email", width: 220 },
      { name: "cust_addr1", label: "Address 1", table: false },
      { name: "cust_addr2", label: "Address 2", table: false },
      { name: "cust_addr3", label: "Address 3", table: false },
    ],
    deleteConfig: { mode: "disabled", payload: () => null, reason: "Delete endpoint is not registered in the existing backend" },
  },
  supplier: {
    title: "Supplier Master",
    subtitle: "Maintain supplier details with currency, country, and contacts.",
    master: "supplier",
    gmEndpoint: "supplier",
    routeKeys: ["supplier"],
    keyField: "supp_code",
    fields: [
      { name: "supp_code", label: "Supplier Code", required: true, disabledOnEdit: true, width: 150 },
      { name: "supp_name", label: "Supplier Name", required: true, width: 280 },
      { name: "curr_code", label: "Currency", width: 130 },
      { name: "country_code", label: "Country Code", width: 140 },
      { name: "supp_city", label: "City", width: 150 },
      { name: "supp_contact1", label: "Contact", width: 180 },
      { name: "supp_telno1", label: "Telephone", width: 150 },
      { name: "supp_email1", label: "Email", type: "email", width: 220 },
      { name: "supp_addr1", label: "Address 1", table: false },
      { name: "supp_addr2", label: "Address 2", table: false },
      { name: "supp_addr3", label: "Address 3", table: false },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.supp_code] },
  },
  product: {
    title: "Product Master",
    subtitle: "Maintain product identity, principal, group, brand, UOM, and packing setup.",
    master: "product",
    gmEndpoint: "product",
    routeKeys: ["product"],
    keyField: "prod_code",
    fields: [
      { name: "prin_code", label: "Principal Code", required: true, width: 150 },
      { name: "prod_code", label: "Product Code", required: true, disabledOnEdit: true, width: 160 },
      { name: "prod_name", label: "Product Name", required: true, width: 320 },
      { name: "group_code", label: "Group Code", width: 140 },
      { name: "brand_code", label: "Brand Code", width: 140 },
      { name: "p_uom", label: "Purchase UOM", width: 140 },
      { name: "l_uom", label: "Loose UOM", width: 130 },
      { name: "upp", label: "UPP", type: "number", width: 110 },
      { name: "barcode", label: "Barcode", width: 170 },
      { name: "prod_type", label: "Product Type", width: 150 },
      { name: "prod_desc", label: "Description", table: false },
    ],
    deleteConfig: { mode: "rawDelete", payload: (row) => [{ prod_code: row.prod_code, prin_code: row.prin_code }] },
  },
  site: {
    title: "Site Master",
    subtitle: "Maintain site setup with warehouse, division, type, and storage behavior.",
    master: "site",
    gmEndpoint: "siteMaster",
    routeKeys: ["site", "sitemaster", "site_master"],
    keyField: "site_code",
    fields: [
      { name: "site_code", label: "Site Code", required: true, disabledOnEdit: true, width: 140 },
      { name: "site_name", label: "Site Name", required: true, width: 260 },
      { name: "site_ind", label: "Site Indicator", width: 130 },
      { name: "site_type", label: "Site Type", width: 130 },
      { name: "country_code", label: "Country Code", width: 140 },
      { name: "wh_code", label: "Warehouse Code", width: 160 },
      { name: "div_code", label: "Division Code", width: 140 },
      { name: "loc_type", label: "Location Type", width: 150 },
      { name: "site_uom", label: "Site UOM", width: 130 },
      { name: "inc_storage", label: "Include Storage", type: "select", options: yesNo, width: 150 },
      { name: "status", label: "Status", type: "select", options: activeInactive, width: 120 },
    ],
    defaults: { inc_storage: "N", status: "A" },
    deleteConfig: { mode: "disabled", payload: () => null, reason: "Delete endpoint is not registered in the existing backend" },
  },
  warehouse: {
    title: "Warehouse Master",
    subtitle: "Maintain warehouse code, address, country, city, and contact information.",
    master: "warehouse",
    gmEndpoint: "warehouse",
    routeKeys: ["warehouse"],
    keyField: "wh_code",
    fields: [
      { name: "wh_code", label: "Warehouse Code", required: true, disabledOnEdit: true, width: 160 },
      { name: "wh_name", label: "Warehouse Name", required: true, width: 280 },
      { name: "country_code", label: "Country Code", width: 140 },
      { name: "city", label: "City", width: 150 },
      { name: "phone", label: "Phone", width: 150 },
      { name: "address", label: "Address", table: false },
    ],
    deleteConfig: { mode: "disabled", payload: () => null, reason: "Delete endpoint is not registered in the existing backend" },
  },
  location: {
    title: "Location Master",
    subtitle: "Maintain warehouse location code, type, status, physical dimensions, and site.",
    master: "location",
    gmEndpoint: "location",
    routeKeys: ["location"],
    keyField: "location_code",
    fields: [
      { name: "site_code", label: "Site Code", required: true, width: 140 },
      { name: "location_code", label: "Location Code", required: true, disabledOnEdit: true, width: 170 },
      { name: "loc_desc", label: "Description", width: 260 },
      { name: "loc_type", label: "Location Type", width: 150 },
      { name: "loc_stat", label: "Status", width: 120 },
      { name: "aisle", label: "Aisle", width: 110 },
      { name: "column_no", label: "Column", width: 110 },
      { name: "height", label: "Height", type: "number", width: 110 },
      { name: "loc_cbm", label: "CBM", type: "number", width: 110 },
      { name: "loc_wt", label: "Weight", type: "number", width: 110 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.location_code] },
  },
  assetgroup: {
    title: "Asset Group Master",
    subtitle: "Maintain WMS asset group codes and names.",
    master: "assetgroup",
    gmEndpoint: "assetgroup",
    routeKeys: ["assetgroup", "asset_group", "asset-group"],
    keyField: "asset_group_code",
    fields: [
      { name: "asset_group_code", label: "Asset Group Code", required: true, disabledOnEdit: true, width: 180 },
      { name: "asset_group_name", label: "Asset Group Name", required: true, width: 280 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.asset_group_code] },
  },
  currency: {
    title: "Currency Master",
    subtitle: "Maintain currency code, name, exchange rate, division, subdivision, and sign.",
    master: "currency",
    gmEndpoint: "currency",
    keyField: "curr_code",
    fields: [
      { name: "curr_code", label: "Currency Code", required: true, disabledOnEdit: true, width: 130 },
      { name: "curr_name", label: "Currency Name", required: true, width: 220 },
      { name: "ex_rate", label: "Exchange Rate", type: "number", width: 130 },
      { name: "division", label: "Division", required: true, width: 130 },
      { name: "subdivision", label: "Sub Division", type: "number", required: true, width: 130 },
      { name: "curr_sign", label: "Currency Sign", width: 120 },
    ],
    defaults: { ex_rate: 1, subdivision: 100 },
    deleteConfig: { mode: "registered", payload: (row) => [row.curr_code] },
  },
  uom: {
    title: "UOM Master",
    subtitle: "Maintain unit of measurement codes used by product and warehouse transactions.",
    master: "uom",
    gmEndpoint: "uom",
    keyField: "uom_code",
    fields: [
      { name: "uom_code", label: "UOM Code", required: true, disabledOnEdit: true, width: 140 },
      { name: "uom_name", label: "UOM Name", required: true, width: 260 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.uom_code] },
  },
  uoc: {
    title: "UOC Master",
    subtitle: "Maintain unit of charge records for WMS billing activity.",
    master: "uoc",
    gmEndpoint: "uoc",
    keyField: "charge_code",
    fields: [
      { name: "charge_code", label: "Charge Code", required: true, width: 140 },
      { name: "description", label: "Description", required: true, width: 260 },
      { name: "activity_group_code", label: "Activity Group", required: true, width: 170 },
      { name: "charge_type", label: "Charge Type", required: true, width: 140 },
    ],
    mapBeforeSave: (form, { editMode, original }) => ({
      ...form,
      ...(editMode
        ? {
            old_charge_code: original?.charge_code || form.charge_code,
            old_charge_type: original?.charge_type || form.charge_type,
          }
        : {}),
    }),
    deleteConfig: { mode: "registered", payload: (row) => [{ company_code: row.company_code, charge_type: row.charge_type, charge_code: row.charge_code }] },
  },
  brand: {
    title: "Brand Master",
    subtitle: "Maintain brand setup by principal and group with preferred storage ranges.",
    master: "brand",
    gmEndpoint: "brand",
    keyField: "brand_code",
    fields: [
      { name: "brand_code", label: "Brand Code", disabledOnEdit: true, width: 130 },
      { name: "prin_code", label: "Principal Code", required: true, width: 150 },
      { name: "group_code", label: "Group Code", required: true, width: 150 },
      { name: "brand_name", label: "Brand Name", required: true, width: 230 },
      { name: "pref_site", label: "Preferred Site", width: 140 },
      { name: "pref_loc_from", label: "Location From", width: 150 },
      { name: "pref_loc_to", label: "Location To", width: 150 },
    ],
    mapBeforeSave: (form, { editMode, original }) => ({
      ...form,
      ...(editMode
        ? {
            old_prin_code: original?.prin_code || form.prin_code,
            old_group_code: original?.group_code || form.group_code,
          }
        : {}),
    }),
    deleteConfig: {
      mode: "registered",
      payload: (row) => [{ company_code: row.company_code, prin_code: row.prin_code, group_code: row.group_code, brand_code: row.brand_code }],
    },
  },
  group: {
    title: "Group Master",
    subtitle: "Maintain product groups by principal with optional storage preferences.",
    master: "group",
    gmEndpoint: "group",
    keyField: "group_code",
    fields: [
      { name: "group_code", label: "Group Code", disabledOnEdit: true, width: 140 },
      { name: "prin_code", label: "Principal Code", required: true, width: 160 },
      { name: "group_name", label: "Group Name", required: true, width: 260 },
      { name: "pref_site", label: "Preferred Site", width: 140 },
      { name: "expiry_cons_days", label: "Expiry Cons. Days", type: "number", width: 150 },
    ],
    deleteConfig: {
      mode: "rawDelete",
      payload: (row) => [{ group_code: row.group_code, prin_code: row.prin_code, company_code: row.company_code }],
    },
  },
  line: {
    title: "Line Master",
    subtitle: "Maintain shipping line codes and names.",
    master: "line",
    gmEndpoint: "line",
    keyField: "line_code",
    fields: [
      { name: "line_code", label: "Line Code", required: true, disabledOnEdit: true, width: 140 },
      { name: "line_name", label: "Line Name", required: true, width: 260 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.line_code] },
  },
  vessel: {
    title: "Vessel Master",
    subtitle: "Maintain vessel details, line, contact, and communication information.",
    master: "vessel",
    gmEndpoint: "vessel",
    keyField: "vessel_code",
    fields: [
      { name: "vessel_code", label: "Vessel Code", required: true, width: 140 },
      { name: "vessel_name", label: "Vessel Name", required: true, width: 240 },
      { name: "line_code", label: "Line Code", width: 140 },
      { name: "contact_person", label: "Contact Person", width: 180 },
      { name: "tel_no", label: "Telephone", width: 140 },
      { name: "email", label: "Email", type: "email", width: 220 },
      { name: "address", label: "Address", table: false },
      { name: "fax_no", label: "Fax No", table: false },
    ],
    mapBeforeSave: (form, { editMode, original }) => ({
      ...form,
      ...(editMode
        ? {
            original_vessel_code: original?.vessel_code || form.vessel_code,
            original_company_code: original?.company_code || form.company_code,
          }
        : {}),
    }),
    deleteConfig: { mode: "registered", payload: (row) => [{ vessel_code: row.vessel_code, company_code: row.company_code }] },
  },
  airline: {
    title: "Airline Master",
    subtitle: "Maintain airline codes and names.",
    master: "airline",
    gmEndpoint: "airline",
    keyField: "airline_code",
    fields: [
      { name: "airline_code", label: "Airline Code", required: true, width: 150 },
      { name: "airline_name", label: "Airline Name", required: true, width: 280 },
      { name: "airline_no", label: "Airline No", width: 140 },
      { name: "contact_person", label: "Contact Person", width: 180 },
      { name: "tel_no", label: "Telephone", width: 140 },
      { name: "email", label: "Email", type: "email", width: 220 },
      { name: "address", label: "Address", table: false },
      { name: "fax_no", label: "Fax No", table: false },
    ],
    mapBeforeSave: (form, { editMode, original }) => ({
      ...form,
      ...(editMode ? { old_airline_code: original?.airline_code || form.airline_code } : {}),
    }),
    deleteConfig: { mode: "registered", payload: (row) => [{ airline_code: row.airline_code, company_code: row.company_code }] },
  },
  
};

export { yesNo };
