import type { WmsSimpleMasterConfig } from "./WmsSimpleMasterPage";

const yesNo = [
  { label: "No", value: "N" },
  { label: "Yes", value: "Y" },
];

const activeInactive = [
  { label: "Active", value: "A" },
  { label: "Inactive", value: "I" },
];

const transportMode = [
  { label: "Sea", value: "S" },
  { label: "Air", value: "A" },
  { label: "Road", value: "R" },
];

export const wmsSimpleMasterConfigs: Record<string, WmsSimpleMasterConfig> = {
  producttype: {
    title: "Product Type Master",
    subtitle: "Maintain product type codes used by product and inbound setup.",
    master: "producttype",
    gmEndpoint: "producttype",
    routeKeys: ["producttype", "product_type", "product-type"],
    keyField: "prodtype_code",
    fields: [
      { name: "prodtype_code", label: "Product Type Code", required: true, disabledOnEdit: true, width: 170 },
      { name: "prodtype_desc", label: "Product Type Description", required: true, width: 280 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.prodtype_code] },
  },
country: {
  title: "Country Master",
  subtitle: "Maintain country code, country name, GCC flag, short description, and nationality.",
  master: "country",
  gmEndpoint: "country",
  routeKeys: ["country"],
  keyField: "country_code",
  formTabs: [
    { key: "basic", label: "Basic Info" },
    { key: "extra", label: "Extra Details" },
  ],
  fields: [
    { name: "country_code", label: "Country Code", required: true, disabledOnEdit: true, width: 150, tab: "basic" },
    { name: "country_name", label: "Country Name", required: true, width: 260, tab: "basic" },
    { name: "gcc_flag",     label: "GCC",           type: "select", options: yesNo, width: 100, tab: "basic" },
    { name: "short_desc",   label: "Short Description", width: 200, tab: "extra" },
    { name: "nationality",  label: "Nationality",   width: 180, tab: "extra" },
  ],
  defaults: { gcc_flag: "N" },
  deleteConfig: { mode: "registered", payload: (row) => [row.country_code] },
},
  activitygroup: {
    title: "Activity Group Master",
    subtitle: "Maintain WMS activity groups, validation behavior, accounting links, and reporting group.",
    master: "activitygroup",
    gmEndpoint: "activitygroup",
    routeKeys: ["activitygroup", "activity_group", "activity-group"],
    keyField: "activity_group_code",
    fields: [
      { name: "activity_group_code", label: "Activity Group Code", required: true, disabledOnEdit: true, width: 180 },
      { name: "act_group_name", label: "Activity Group Name", required: true, width: 260 },
      { name: "mandatory_flag", label: "Mandatory", type: "select", options: yesNo, width: 120 },
      { name: "validate_flag", label: "Validate", type: "select", options: yesNo, width: 120 },
      { name: "act_group_type", label: "Group Type", width: 140 },
      { name: "account_code", label: "Account Code", width: 150 },
      { name: "alternate_accode", label: "Alternate Account", width: 160 },
      { name: "exp_account_code", label: "Expense Account", width: 160 },
      { name: "freight_flag", label: "Freight", type: "select", options: yesNo, width: 110 },
      { name: "sw_flag", label: "SW Flag", type: "select", options: yesNo, width: 110 },
      { name: "rpt_group_name", label: "Report Group", width: 180 },
      { name: "sort_order", label: "Sort Order", type: "number", width: 120 },
      { name: "cost_group", label: "Cost Group", width: 140 },
    ],
    defaults: { mandatory_flag: "N", validate_flag: "N", freight_flag: "N", sw_flag: "N" },
    deleteConfig: { mode: "registered", payload: (row) => [row.activity_group_code] },
  },
  activitysubgroup: {
    title: "Activity Sub Group Master",
    subtitle: "Maintain activity sub groups linked with WMS activity groups.",
    master: "activitysubgroup",
    gmEndpoint: "activitysubgroup",
    routeKeys: ["activitysubgroup", "activity_subgroup", "activity-subgroup"],
    keyField: "activity_subgroup_code",
    fields: [
      { name: "activity_subgroup_code", label: "Sub Group Code", required: true, disabledOnEdit: true, width: 170 },
      { name: "act_subgroup_name", label: "Sub Group Name", required: true, width: 260 },
      { name: "act_group_code", label: "Activity Group Code", required: true, width: 180 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.activity_subgroup_code] },
  },
  activitykpi: {
    title: "Activity KPI Master",
    subtitle: "Maintain expected hours by principal, activity, customer, and job type.",
    master: "activitykpi",
    gmEndpoint: "activity-kpi",
    routeKeys: ["activity-kpi", "activitykpi", "activity_kpi"],
    keyField: "act_code",
    fields: [
      { name: "prin_code", label: "Principal Code", required: true, width: 160 },
      { name: "job_type", label: "Job Type", required: true, width: 130 },
      { name: "act_code", label: "Activity Code", required: true, width: 150 },
      { name: "cust_code", label: "Customer Code", required: true, width: 150 },
      { name: "exp_hours", label: "Expected Hours", type: "number", width: 150 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.prin_code] },
  },
  department: {
    title: "Department Master",
    subtitle: "Maintain department code, name, and division link.",
    master: "department",
    gmEndpoint: "department",
    routeKeys: ["department"],
    keyField: "dept_code",
    fields: [
      { name: "dept_code", label: "Department Code", required: true, disabledOnEdit: true, width: 170 },
      { name: "dept_name", label: "Department Name", required: true, width: 260 },
      { name: "div_code", label: "Division Code", dropdownParam: "DROP_DOWN_DIVISION", width: 150, required: true },
    ],
    deleteConfig: { mode: "rawDelete", payload: (row) => ({ ids: [row.dept_code] }) },
  },
  division: {
    title: "Division Master",
    subtitle: "Maintain division identity, address, contacts, and status.",
    master: "division",
    gmEndpoint: "division",
    routeKeys: ["division"],
    keyField: "div_code",
    fields: [
      { name: "div_code", label: "Division Code", required: true, disabledOnEdit: true, width: 150 },
      { name: "div_name", label: "Division Name", required: true, width: 260 },
      { name: "div_short_name", label: "Short Name", width: 150 },
      { name: "country_code", label: "Country Code", width: 140 },
      { name: "phone", label: "Phone", width: 150 },
      { name: "fax", label: "Fax", width: 140 },
      { name: "email", label: "Email", type: "email", width: 220 },
      { name: "status", label: "Status", type: "select", options: activeInactive, width: 120 },
      { name: "div_address1", label: "Address 1", table: false },
      { name: "div_address2", label: "Address 2", table: false },
      { name: "div_address3", label: "Address 3", table: false },
      { name: "remarks", label: "Remarks", table: false },
    ],
    defaults: { status: "A" },
    deleteConfig: { mode: "rawDelete", payload: (row) => [{ company_code: row.company_code, div_code: row.div_code }] },
  },
  manufacture: {
    title: "Manufacturer Master",
    subtitle: "Maintain manufacturer codes by principal.",
    master: "manufacturer",
    gmEndpoint: "manufacture",
    routeKeys: ["manufacture", "manufacturer"],
    keyField: "manu_code",
    fields: [
      { name: "prin_code", label: "Principal Code", required: true, asyncOptions: { endpoint: "principal", labelKey: "prin_name", valueKey: "prin_code" }, width: 150 },
      { name: "manu_code", label: "Manufacturer Code", required: true, disabledOnEdit: true, width: 180 },
      { name: "manu_name", label: "Manufacturer Name", required: true, width: 280 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [{ manu_code: row.manu_code, prin_code: row.prin_code }] },
  },
  moc2: {
    title: "MOC2 Master",
    subtitle: "Maintain charge codes, charge type, and activity group mapping.",
    master: "moc2",
    gmEndpoint: "moc2",
    routeKeys: ["moc2"],
    keyField: "charge_code",
    fields: [
      { name: "charge_code", label: "Charge Code", required: true, width: 150 },
      { name: "description", label: "Description", required: true, width: 260 },
      { name: "charge_type", label: "Charge Type", required: true, width: 140 },
      { name: "activity_group_code", label: "Activity Group", required: true, width: 170 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [{ charge_code: row.charge_code, charge_type: row.charge_type, company_code: row.company_code }] },
  },
  moc: {
    title: "MOC Master",
    subtitle: "Maintain mode of collection codes and activity group mapping.",
    master: "moc",
    gmEndpoint: "moc",
    routeKeys: ["moc"],
    keyField: "moc_code",
    fields: [
      { name: "moc_code", label: "MOC Code", required: true, disabledOnEdit: true, width: 140 },
      { name: "moc_name", label: "MOC Name", required: true, width: 260 },
      { name: "activity_group_code", label: "Activity Group", width: 170 },
      { name: "description", label: "Description", width: 260 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => ({ moc_code: row.moc_code, company_code: row.company_code }) },
  },
  harmonize: {
    title: "Harmonize Code Master",
    subtitle: "Maintain harmonized commodity and customs reference codes.",
    master: "harmonize",
    gmEndpoint: "harmonize",
    routeKeys: ["harmonize"],
    keyField: "harm_code",
    fields: [
      { name: "harm_code", label: "Harmonize Code", required: true, disabledOnEdit: true, width: 170 },
      { name: "harm_desc", label: "Description", required: true, width: 320 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.harm_code] },
  },
  port: {
    title: "Port Master",
    subtitle: "Maintain port codes by country and transport mode.",
    master: "port",
    gmEndpoint: "port",
    routeKeys: ["port"],
    keyField: "port_code",
    fields: [
      { name: "port_code", label: "Port Code", required: true, disabledOnEdit: true, width: 140 },
      { name: "port_name", label: "Port Name", required: true, width: 260 },
      { name: "country_code", label: "Country Code", width: 150 },
      { name: "trp_mode", label: "Transport Mode", type: "select", options: transportMode, width: 150 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.port_code] },
  },
  partner: {
    title: "Partner Master",
    subtitle: "Maintain broker and partner contact information.",
    master: "partner",
    gmEndpoint: "partner",
    routeKeys: ["partner", "broker"],
    keyField: "broker_code",
    fields: [
      { name: "broker_code", label: "Partner Code", required: true, disabledOnEdit: true, width: 150 },
      { name: "broker_name", label: "Partner Name", required: true, width: 260 },
      { name: "country_code", label: "Country Code", width: 140 },
      { name: "broker_city", label: "City", width: 150 },
      { name: "broker_contact1", label: "Contact", width: 180 },
      { name: "broker_telno1", label: "Telephone", width: 150 },
      { name: "broker_email1", label: "Email", type: "email", width: 220 },
      { name: "broker_addr1", label: "Address 1", table: false },
      { name: "broker_addr2", label: "Address 2", table: false },
      { name: "broker_addr3", label: "Address 3", table: false },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.broker_code] },
  },
  locationtype: {
    title: "Location Type Master",
    subtitle: "Maintain warehouse location dimensions and push level setup.",
    master: "locationtype",
    gmEndpoint: "locationtype",
    routeKeys: ["locationtype", "location_type", "location-type"],
    keyField: "loc_type",
    fields: [
      { name: "loc_type", label: "Location Type", required: true, disabledOnEdit: true, width: 150 },
      { name: "loc_name", label: "Location Name", required: true, width: 240 },
      { name: "loc_cbm", label: "CBM", type: "number", width: 120 },
      { name: "loc_wt", label: "Weight", type: "number", width: 120 },
      { name: "push_level", label: "Push Level", type: "number", width: 130 },
    ],
    deleteConfig: { mode: "disabled", payload: () => null, reason: "Delete endpoint is not registered in the existing backend" },
  },
  salesman: {
    title: "Salesman Master",
    subtitle: "Maintain salesman codes and names.",
    master: "salesman",
    gmEndpoint: "salesman",
    routeKeys: ["salesman"],
    keyField: "salesman_code",
    fields: [
      { name: "salesman_code", label: "Salesman Code", required: true, disabledOnEdit: true, width: 160 },
      { name: "salesman_name", label: "Salesman Name", required: true, width: 280 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.salesman_code] },
  },
  alert: {
    title: "Alert Master",
    subtitle: "Maintain operational alert sequence, module, mode, and instruction text.",
    master: "alert",
    gmEndpoint: "alert",
    routeKeys: ["alert"],
    keyField: "op_code",
    fields: [
      { name: "op_type", label: "Operation Type", required: true, width: 150 },
      { name: "op_code", label: "Operation Code", required: true, width: 160 },
      { name: "op_desc", label: "Description", required: true, width: 260 },
      { name: "op_sequence", label: "Sequence", type: "number", width: 120 },
      { name: "op_module", label: "Module", width: 130 },
      { name: "op_mode", label: "Mode", width: 120 },
      { name: "instruction", label: "Instruction", table: false },
    ],
    saveEndpoint: (form, { editMode, original }) =>
      editMode ? `alert/${original?.op_type || form.op_type}/${original?.op_code || form.op_code}` : "alert",
    deleteConfig: { mode: "registered", payload: (row) => [{ op_type: row.op_type, op_code: row.op_code, company_code: row.company_code }] },
  },
  principal: {
    title: "Principal Master",
    subtitle: "Maintain principal identity, division, country, currency, and primary contact details.",
    master: "principal",
    gmEndpoint: "principal",
    routeKeys: ["principal"],
    keyField: "prin_code",
    fieldsPerRow: 5,
    formTabs: [
      { key: "basic-info", label: "Basic Info" },
      { key: "contact-info", label: "Contact Info" },
      { key: "organization", label: "Organization" },
      { key: "account-info", label: "Account Info" },
      { key: "settings", label: "Settings" },
      { key: "storage-info", label: "Storage Info" },
    ],
    fields: [
      // Basic Info Tab - Company Details
      { name: "prin_code", label: "Principal Code", disabledOnEdit: true, width: 160, tab: "basic-info", section: "COMPANY DETAILS" },
      { name: "prin_name", label: "Principal Name", required: true, width: 280, tab: "basic-info", section: "COMPANY DETAILS", colSpan: 2 },
      { name: "status", label: "Status", required: true, type: "select", options: [{ label: "Active", value: "A" }, { label: "Inactive", value: "I" }], tab: "basic-info", section: "COMPANY DETAILS" },
      { name: "prin_city", label: "City", width: 280, tab: "basic-info", section: "COMPANY DETAILS" },
      { name: "country_code", label: "Country", required: true, dropdownParam: "DROP_DOWN_COUNTRY",dropdownDisplayFields: ["country_code", "country_name"], dropdownValueKey: "country_code",
      dropdownDisplaySeparator: " - ", tab: "basic-info", section: "COMPANY DETAILS" },
      { name: "prin_addr1", label: "Address 1", type: "textarea", tab: "basic-info", section: "COMPANY DETAILS", colSpan: 2 },
      { name: "prin_addr2", label: "Address 2", type: "textarea", tab: "basic-info", section: "COMPANY DETAILS", colSpan: 2 },
      { name: "prin_addr3", label: "Address 3", type: "textarea", tab: "basic-info", section: "COMPANY DETAILS" },
      { name: "prin_addr4", label: "Address 4", type: "textarea", tab: "basic-info", section: "COMPANY DETAILS" },
      { name: "territory_code", label: "Territory", dropdownParam: "DROP_DOWN_TERRITORY", dropdownCodeMap: { country_code: "code1" }, tab: "basic-info", section: "COMPANY DETAILS" },
      { name: "sector", label: "Sector", tab: "basic-info", section: "COMPANY DETAILS" },
      
      // Basic Info Tab - Contact Information
      { name: "email_account", label: "Email Account", type: "email", tab: "contact-info", section: "CONTACT INFORMATION" },
      { name: "prin_email1", label: "Email 1", type: "email", tab: "contact-info", section: "CONTACT INFORMATION" },
      { name: "email2", label: "Email 2", type: "email", tab: "contact-info", section: "CONTACT INFORMATION" },
      { name: "email3", label: "Email 3", type: "email", tab: "contact-info", section: "CONTACT INFORMATION" },
      { name: "company_fax1", label: "Company Fax 1", tab: "contact-info", section: "CONTACT INFORMATION" },
      { name: "company_fax2", label: "Company Fax 2", tab: "contact-info", section: "CONTACT INFORMATION" },
      { name: "company_fax3", label: "Company Fax 3", tab: "contact-info", section: "CONTACT INFORMATION" },
      { name: "prin_contact1", label: "Contact Person", tab: "contact-info", section: "CONTACT INFORMATION" },
      { name: "prin_telno1", label: "Telephone", tab: "contact-info", section: "CONTACT INFORMATION" },
      
      // Basic Info Tab - Organization
      { name: "div_code", label: "Division", required: true, dropdownParam: "DROP_DOWN_DIVISION", dropdownDisplayFields: ["div_code", "div_name"], dropdownDisplaySeparator: " - ", dropdownValueKey: "div_code", dropdownCodeMap: { company_code: "code1" }, tab: "organization", section: "ORGANIZATION" },
      { name: "dept_code", label: "Department", required: true, dropdownParam: "DROP_DOWN_DEPT_BASED_ON_DIV", dropdownDisplayFields: ["dept_code", "dept_name"], dropdownDisplaySeparator: " - ", dropdownValueKey: "dept_code", dropdownCodeMap: { div_code: "code1" }, tab: "organization", section: "ORGANIZATION" },
      { name: "reference", label: "Reference", tab: "organization", section: "ORGANIZATION" },
      { name: "auto_generate_product_code", label: "Auto Generate Product Code", type: "checkbox", tab: "organization", section: "ORGANIZATION" },

      // Account Info Tab - Company Registration Information
      { name: "tax_reg_no", label: "Tax Registered No.",type: "number", tab: "account-info", section: "COMPANY REGISTRATION INFORMATION" },
      { name: "tax_expiry_date", label: "Tax Reg. Expiry Date", type: "date", tab: "account-info", section: "COMPANY REGISTRATION INFORMATION" },
      { name: "comm_reg_no", type:"number", label: "Commercial Reg. No.", tab: "account-info", section: "COMPANY REGISTRATION INFORMATION" },
      { name: "comm_expiry_date", label: "Commercial Reg. Expiry", type: "date", tab: "account-info", section: "COMPANY REGISTRATION INFORMATION" },
      { name: "license_no", label: "License No.", tab: "account-info", section: "COMPANY REGISTRATION INFORMATION" },
      { name: "license_type", label: "License Type", tab: "account-info", section: "COMPANY REGISTRATION INFORMATION" },
      { name: "curr_code", label: "Default Currency", dropdownParam: "DROP_DOWN_CURRENCY", dropdownDisplayFields: ["curr_code", "curr_name"], dropdownDisplaySeparator: " - ", dropdownValueKey: "curr_code", tab: "account-info", section: "COMPANY REGISTRATION INFORMATION" },
      { name: "in_designated_zone", label: "In Designated Zone", type: "checkbox", tab: "account-info", section: "COMPANY REGISTRATION INFORMATION" },

      // Account Info Tab - Account and Credit Information
      { name: "ac_reference", label: "A/C Reference", tab: "account-info", section: "ACCOUNT AND CREDIT INFORMATION" },
      { name: "credit_limit", label: "Credit Limit", type: "number", tab: "account-info", section: "ACCOUNT AND CREDIT INFORMATION" },
      { name: "credit_period_wms", label: "Credit Period (WMS)", type: "number", tab: "account-info", section: "ACCOUNT AND CREDIT INFORMATION" },
      { name: "credit_freight", label: "Credit Freight", type: "number", tab: "account-info", section: "ACCOUNT AND CREDIT INFORMATION" },

      // Account Info Tab - Invoice and Transaction History
      { name: "import_code", label: "Import Code", tab: "account-info", section: "INVOICE AND TRANSACTION HISTORY" },
      { name: "parent_prin_code", label: "Parent Principal Code", tab: "account-info", section: "INVOICE AND TRANSACTION HISTORY" },
      { name: "last_invoice_date", label: "Last Invoice Date", type: "date", tab: "account-info", section: "INVOICE AND TRANSACTION HISTORY" },

      // Settings Tab - Pick Rules
      { name: "pick_wave", label: "Pick Wave", dropdownParam:"DROP_DOWN_PICK_WAVE", dropdownDisplayFields: [ "wave_code","wave_name"],dropdownDisplaySeparator: " - ", dropdownValueKey: "wave_code", tab: "settings", section: "PICK RULES" },
      { name: "pick_wave_min_exp", label: "Pick Wave (Minimum Exp)", type: "checkbox", tab: "settings", section: "PICK RULES" },
      { name: "pick_wave_least_qty", label: "Pick Wave (Least Quantity)", type: "checkbox", tab: "settings", section: "PICK RULES" },

      // Settings Tab - General Settings
      { name: "allow_undervalue", label: "Allow Undervalue", type: "checkbox", tab: "settings", section: "GENERAL SETTINGS" },
      { name: "auto_populate_bill", label: "Auto Populate Bill", type: "checkbox", tab: "settings", section: "GENERAL SETTINGS" },
      { name: "chargeable", label: "Chargeable", type: "checkbox", tab: "settings", section: "GENERAL SETTINGS" },
      { name: "export_price_check", label: "Export Price Check", type: "checkbox", tab: "settings", section: "GENERAL SETTINGS" },
      { name: "compute_landed_cost", label: "Compute Landed Cost", type: "checkbox", tab: "settings", section: "GENERAL SETTINGS" },
      { name: "auto_job_no_generate", label: "Auto Job No Generate", type: "checkbox", tab: "settings", section: "GENERAL SETTINGS" },
      { name: "validate_lot_no", label: "Validate Lot No.", type: "checkbox", tab: "settings", section: "GENERAL SETTINGS" },
      { name: "automate_activity", label: "Automate Activity", type: "checkbox", tab: "settings", section: "GENERAL SETTINGS" },

      // Settings Tab - Product and Shipment Settings
      { name: "product_wise_storage", label: "Product Wise Storage", type: "checkbox", tab: "settings", section: "PRODUCT AND SHIPMENT SETTINGS" },
      { name: "direct_shipment", label: "Direct Shipment", type: "checkbox", tab: "settings", section: "PRODUCT AND SHIPMENT SETTINGS" },
      { name: "perpetual_confirm_allow", label: "Perpetual Confirm Allow", type: "checkbox", tab: "settings", section: "PRODUCT AND SHIPMENT SETTINGS" },
      { name: "outbound_validate_exp_date", label: "Outbound Validate Exp Date", type: "text", tab: "settings", section: "PRODUCT AND SHIPMENT SETTINGS" },
      { name: "outbound_min_exp_period", label: "Outbound Min Exp Period", type: "text", tab: "settings", section: "PRODUCT AND SHIPMENT SETTINGS" },
      { name: "inbound_exp_limit_days", label: "Inbound Exp Limit (days)", type: "number", tab: "settings", section: "PRODUCT AND SHIPMENT SETTINGS" },

      // Storage Info Tab - Location
      { name: "preferred_site", label: "Preferred Site", type: "select", tab: "storage-info", section: "LOCATION" },
      { name: "location_from", label: "Location From", type: "select", tab: "storage-info", section: "LOCATION" },
      { name: "location_to", label: "Location To", type: "select", tab: "storage-info", section: "LOCATION" },
      { name: "aisle_from", label: "Aisle From", tab: "storage-info", section: "LOCATION" },
      { name: "aisle_to", label: "Aisle To", tab: "storage-info", section: "LOCATION" },
      { name: "column_from", label: "Column From", tab: "storage-info", section: "LOCATION" },
      { name: "column_to", label: "Column To", tab: "storage-info", section: "LOCATION" },

      // Storage Info Tab - Site, Service and Storage Details
      { name: "height_from", label: "Height From", type: "number", tab: "storage-info", section: "SITE, SERVICE AND STORAGE DETAILS" },
      { name: "height_to", label: "Height To", type: "number", tab: "storage-info", section: "SITE, SERVICE AND STORAGE DETAILS" },
      { name: "default_site_ind", label: "Default Site Ind", type: "select", tab: "storage-info", section: "SITE, SERVICE AND STORAGE DETAILS" },
      { name: "service_date", label: "Service Date", type: "date", tab: "storage-info", section: "SITE, SERVICE AND STORAGE DETAILS" },
      { name: "storage_type", label: "Storage Type", type: "select", tab: "storage-info", section: "SITE, SERVICE AND STORAGE DETAILS" },
      { name: "default_foc", label: "Default Foc", type: "select", tab: "storage-info", section: "SITE, SERVICE AND STORAGE DETAILS" },
    ],
    mapBeforeSave: (form) => ({
      // Basic Info
      prin_code: form.prin_code,
      prin_name: form.prin_name,
      prin_status: form.status,
      prin_city: form.prin_city,
      country_code: form.country_code,
      tax_country_code: form.tax_country_code || "",
      tax_country_sn: form.tax_country_sn || "",
      prin_addr1: form.prin_addr1,
      prin_addr2: form.prin_addr2,
      prin_addr3: form.prin_addr3,
      prin_addr4: form.prin_addr4,
      territory_code: form.territory_code,
      sector_code: form.sector,
      
      // Contact Info - Primary
      acc_email: form.email_account,
      prin_email1: form.prin_email1,
      prin_email2: form.email2,
      prin_email3: form.email3,
      prin_faxno1: form.company_fax1,
      prin_faxno2: form.company_fax2,
      prin_faxno3: form.company_fax3,
      
      // Contact Info - Secondary (Additional contacts)
      prin_cont1: form.prin_contact1 || "",
      prin_cont2: form.prin_contact2 || "",
      prin_cont3: form.prin_contact3 || "",
      prin_cont_email1: form.prin_contact_email1 || "",
      prin_cont_email2: form.prin_contact_email2 || "",
      prin_cont_email3: form.prin_contact_email3 || "",
      prin_cont_telno1: form.prin_telno1 || "",
      prin_cont_telno2: form.prin_telno2 || "",
      prin_cont_telno3: form.prin_telno3 || "",
      prin_cont_faxno1: form.prin_contact_fax1 || "",
      prin_cont_faxno2: form.prin_contact_fax2 || "",
      prin_cont_faxno3: form.prin_contact_fax3 || "",
      prin_cont_ref1: form.prin_contact_ref1 || "",
      
      // Organization
      div_code: form.div_code,
      prin_dept_code: form.dept_code,
      prin_ref1: form.reference,
      auto_generate_product_code: form.auto_generate_product_code,
      
      // Account Info - Company Registration
      trn_no: form.tax_reg_no || null,
      trn_exp_date: form.tax_expiry_date || null,
      comm_reg_no: form.comm_reg_no || null,
      comm_reg_exp_date: form.comm_expiry_date || null,
      prin_lic_no: form.license_no || null,
      prin_lic_type: form.license_type,
      curr_code: form.curr_code,
      prin_infze: form.in_designated_zone,
      
      // Account Info - Credit
      prin_acref: form.ac_reference,
      credit_limit: form.credit_limit || null,
      creditdays: form.credit_period_wms || null,
      creditdays_freight: form.credit_freight || null,
      
      // Account Info - Transaction
      prin_imp_code: form.import_code,
      parent_prin_code: form.parent_prin_code,
      prin_invdate: form.last_invoice_date || null,
      
      // Files (for document upload if needed)
      files: form.files || [],
      
      // Settings - Pick Rules
      pick_wave: form.pick_wave,
      pick_wave_ign_min_exp: form.pick_wave_min_exp,
      pick_wave_qty_sort: form.pick_wave_least_qty,
      
      // Settings - General
      under_value: form.allow_undervalue,
      auto_insert_billactivity: form.auto_populate_bill,
      prin_charge: form.chargeable,
      prin_pricechk: form.export_price_check,
      prin_landedpr: form.compute_landed_cost,
      auto_job: form.auto_job_no_generate,
      validate_lotno: form.validate_lot_no,
      
      // Settings - Product and Shipment
      storage_productwise: form.product_wise_storage,
      dir_shpmnt: form.direct_shipment,
      perpectual_confirm_allow: form.perpetual_confirm_allow,
      validate_expdate: form.outbound_validate_exp_date || null,
      minperiod_exppick: form.outbound_min_exp_period || null,
      rcpt_exp_limit: form.inbound_exp_limit_days || null,
      
      // Storage
      pref_site: form.preferred_site,
      pref_loc_from: form.location_from,
      pref_loc_to: form.location_to,
      pref_aisle_from: form.aisle_from || null,
      pref_aisle_to: form.aisle_to || null,
      pref_col_from: form.column_from || null,
      pref_col_to: form.column_to || null,
      pref_ht_from: form.height_from || null,
      pref_ht_to: form.height_to || null,
      prin_siteind: form.default_site_ind,
      service_date: form.service_date || null,
      storage_type: form.storage_type,
      default_foc: form.default_foc,
      automate_activity: form.automate_activity,
      
      // Company code (handled separately in saveRecord)
      company_code: form.company_code,
    }),
    mapAfterLoad: (data) => ({
      // Basic Info
      prin_code: data.prin_code,
      prin_name: data.prin_name,
      status: data.prin_status,
      prin_city: data.prin_city,
      country_code: data.country_code,
      tax_country_code: data.tax_country_code || "",
      tax_country_sn: data.tax_country_sn || "",
      prin_addr1: data.prin_addr1,
      prin_addr2: data.prin_addr2,
      prin_addr3: data.prin_addr3,
      prin_addr4: data.prin_addr4,
      territory_code: data.territory_code,
      sector: data.sector_code,
      
      // Contact Info - Primary
      email_account: data.acc_email,
      prin_email1: data.prin_email1,
      email2: data.prin_email2,
      email3: data.prin_email3,
      company_fax1: data.prin_faxno1,
      company_fax2: data.prin_faxno2,
      company_fax3: data.prin_faxno3,
      
      // Contact Info - Secondary (Additional contacts)
      prin_contact1: data.prin_cont1 || "",
      prin_contact2: data.prin_cont2 || "",
      prin_contact3: data.prin_cont3 || "",
      prin_contact_email1: data.prin_cont_email1 || "",
      prin_contact_email2: data.prin_cont_email2 || "",
      prin_contact_email3: data.prin_cont_email3 || "",
      prin_telno1: data.prin_cont_telno1 || "",
      prin_telno2: data.prin_cont_telno2 || "",
      prin_telno3: data.prin_cont_telno3 || "",
      prin_contact_fax1: data.prin_cont_faxno1 || "",
      prin_contact_fax2: data.prin_cont_faxno2 || "",
      prin_contact_fax3: data.prin_cont_faxno3 || "",
      prin_contact_ref1: data.prin_cont_ref1 || "",
      
      // Organization
      div_code: data.div_code,
      dept_code: data.prin_dept_code,
      reference: data.prin_ref1,
      auto_generate_product_code: data.auto_generate_product_code,
      
      // Account Info - Company Registration
      tax_reg_no: data.trn_no || null,
      tax_expiry_date: data.trn_exp_date || null,
      comm_reg_no: data.comm_reg_no || null,
      comm_expiry_date: data.comm_reg_exp_date || null,
      license_no: data.prin_lic_no || null,
      license_type: data.prin_lic_type,
      curr_code: data.curr_code,
      in_designated_zone: data.prin_infze,
      
      // Account Info - Credit
      ac_reference: data.prin_acref,
      credit_limit: data.credit_limit || null,
      credit_period_wms: data.creditdays || null,
      credit_freight: data.creditdays_freight || null,
      
      // Account Info - Transaction
      import_code: data.prin_imp_code,
      parent_prin_code: data.parent_prin_code,
      last_invoice_date: data.prin_invdate || null,
      
      // Files
      files: data.files || [],
      
      // Settings - Pick Rules
      pick_wave: data.pick_wave,
      pick_wave_min_exp: data.pick_wave_ign_min_exp,
      pick_wave_least_qty: data.pick_wave_qty_sort,
      
      // Settings - General
      allow_undervalue: data.under_value,
      auto_populate_bill: data.auto_insert_billactivity,
      chargeable: data.prin_charge,
      export_price_check: data.prin_pricechk,
      compute_landed_cost: data.prin_landedpr,
      auto_job_no_generate: data.auto_job,
      validate_lot_no: data.validate_lotno,
      
      // Settings - Product and Shipment
      product_wise_storage: data.storage_productwise,
      direct_shipment: data.dir_shpmnt,
      perpetual_confirm_allow: data.perpectual_confirm_allow,
      outbound_validate_exp_date: data.validate_expdate || null,
      outbound_min_exp_period: data.minperiod_exppick || null,
      inbound_exp_limit_days: data.rcpt_exp_limit || null,
      
      // Storage
      preferred_site: data.pref_site,
      location_from: data.pref_loc_from,
      location_to: data.pref_loc_to,
      aisle_from: data.pref_aisle_from || null,
      aisle_to: data.pref_aisle_to || null,
      column_from: data.pref_col_from || null,
      column_to: data.pref_col_to || null,
      height_from: data.pref_ht_from || null,
      height_to: data.pref_ht_to || null,
      default_site_ind: data.prin_siteind,
      service_date: data.service_date || null,
      storage_type: data.storage_type,
      default_foc: data.default_foc,
      automate_activity: data.automate_activity,
      
      // Company code
      company_code: data.company_code,
    }),
    saveEndpoint: (form, { editMode, original }) => (editMode ? `principal/${original?.prin_code || form.prin_code}` : "principal"),
    deleteConfig: { mode: "disabled", payload: () => null, reason: "Delete endpoint is not registered in the existing backend" },
  },
  customer: {
    title: "Customer Master",
    subtitle: "Maintain customer details by principal with currency, country, and contacts.",
    master: "customer",
    gmEndpoint: "customer",
    routeKeys: ["customer"],
    keyField: "cust_code",
    fields: [
      { name: "prin_code", label: "Principal Code", required: true, width: 150 },
      { name: "cust_code", label: "Customer Code", required: true, disabledOnEdit: true, width: 150 },
      { name: "cust_name", label: "Customer Name", required: true, width: 280 },
      { name: "curr_code", label: "Currency", width: 130 },
      { name: "country_code", label: "Country Code", width: 140 },
      { name: "cust_city", label: "City", width: 150 },
      { name: "cust_contact1", label: "Contact", width: 180 },
      { name: "cust_telno1", label: "Telephone", width: 150 },
      { name: "cust_email1", label: "Email", type: "email", width: 220 },
      { name: "cust_addr1", label: "Address 1", table: false },
      { name: "cust_addr2", label: "Address 2", table: false },
      { name: "cust_addr3", label: "Address 3", table: false },
    ],
    deleteConfig: { mode: "disabled", payload: () => null, reason: "Delete endpoint is not registered in the existing backend" },
  },
  supplier: {
    title: "Supplier Master",
    subtitle: "Maintain supplier details with currency, country, and contacts.",
    master: "supplier",
    gmEndpoint: "supplier",
    routeKeys: ["supplier"],
    keyField: "supp_code",
    fields: [
      { name: "supp_code", label: "Supplier Code", required: true, disabledOnEdit: true, width: 150 },
      { name: "supp_name", label: "Supplier Name", required: true, width: 280 },
      { name: "curr_code", label: "Currency", width: 130 },
      { name: "country_code", label: "Country Code", width: 140 },
      { name: "supp_city", label: "City", width: 150 },
      { name: "supp_contact1", label: "Contact", width: 180 },
      { name: "supp_telno1", label: "Telephone", width: 150 },
      { name: "supp_email1", label: "Email", type: "email", width: 220 },
      { name: "supp_addr1", label: "Address 1", table: false },
      { name: "supp_addr2", label: "Address 2", table: false },
      { name: "supp_addr3", label: "Address 3", table: false },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.supp_code] },
  },
  // product: {
  //   title: "Product Master",
  //   subtitle: "Maintain product identity, principal, group, brand, UOM, and packing setup.",
  //   master: "product",
  //   gmEndpoint: "product",
  //   routeKeys: ["product"],
  //   keyField: "prod_code",
  //   fields: [
  //     { name: "prin_code", label: "Principal Code", required: true, width: 150 },
  //     { name: "prod_code", label: "Product Code", required: true, disabledOnEdit: true, width: 160 },
  //     { name: "prod_name", label: "Product Name", required: true, width: 320 },
  //     { name: "group_code", label: "Group Code", width: 140 },
  //     { name: "brand_code", label: "Brand Code", width: 140 },
  //     { name: "p_uom", label: "Purchase UOM", width: 140 },
  //     { name: "l_uom", label: "Loose UOM", width: 130 },
  //     { name: "upp", label: "UPP", type: "number", width: 110 },
  //     { name: "barcode", label: "Barcode", width: 170 },
  //     { name: "prod_type", label: "Product Type", width: 150 },
  //     { name: "prod_desc", label: "Description", table: false },
  //   ],
  //   deleteConfig: { mode: "rawDelete", payload: (row) => [{ prod_code: row.prod_code, prin_code: row.prin_code }] },
  // },
product: {
  title: "Product Master",
  subtitle: "Maintain product identity, principal, group, brand, UOM, and packing setup.",
  master: "product",
  gmEndpoint: "product",
  routeKeys: ["product"],
  keyField: "prod_code",
  fieldsPerRow: 5,
  formTabs: [
    { key: "product-details", label: "Product Details" },
    { key: "uom-volume", label: "UOM & Volume" },
    { key: "manufacture-validation", label: "Manufacture & Validation" },
    { key: "category-product", label: "Category & Product" },
  ],
  fields: [
    // Product Details Tab - Principal Info
    { name: "prin_code", label: "Principal Code", required: true, dropdownParam: "DROP_DOWN_PRINCIPAL", width: 150, tab: "product-details", section: "PRINCIPAL INFO" },
    { name: "group_code", label: "Group Code", required: true, dropdownParam: "DROP_DOWN_GROUP", dropdownCodeMap: { prin_code: "code1" }, width: 140, tab: "product-details", section: "PRINCIPAL INFO" },
    { name: "brand_code", label: "Brand Code", required: true, dropdownParam: "DROP_DOWN_BRAND", dropdownCodeMap: { prin_code: "code1", group_code: "code2" }, width: 140, tab: "product-details", section: "PRINCIPAL INFO" },

    // Product Details Tab - Product Info
    { name: "prod_code", label: "Product Code", disabledOnEdit: true, width: 160, tab: "product-details", section: "PRODUCT INFO" },
    { name: "prod_name", label: "Product Name", required: true, width: 320, tab: "product-details", section: "PRODUCT INFO", colSpan: 2 },
    { name: "model", label: "Model #", tab: "product-details", section: "PRODUCT INFO" },
    { name: "variant", label: "Variant", tab: "product-details", section: "PRODUCT INFO" },

    // UOM & Volume Tab - Unit of Measurement
    { name: "no_of_uoms", label: "No. of UOMs", type: "number", tab: "uom-volume", section: "UNIT OF MEASUREMENT" },
    { name: "p_uom", label: "Primary UOM", required: true, dropdownParam: "DROP_DOWN_UOM", width: 140, tab: "uom-volume", section: "UNIT OF MEASUREMENT" },
    { name: "l_uom", label: "Lowest UOM", required: true, dropdownParam: "DROP_DOWN_UOM", width: 130, tab: "uom-volume", section: "UNIT OF MEASUREMENT" },
    { name: "units_prim_pack", label: "Units/Prim Pack", required: true, type: "number", tab: "uom-volume", section: "UNIT OF MEASUREMENT" },
    { name: "def_units_palette", label: "Def. Units/Pallette", required: true, type: "number", tab: "uom-volume", section: "UNIT OF MEASUREMENT" },
    { name: "qty_as_wt", label: "Qty As Wt", type: "checkbox", tab: "uom-volume", section: "UNIT OF MEASUREMENT" },

    // UOM & Volume Tab - Volume
    { name: "length", label: "Length", type: "number", tab: "uom-volume", section: "VOLUME (METER / KILOGRAM)" },
    { name: "width", label: "Width", type: "number", tab: "uom-volume", section: "VOLUME (METER / KILOGRAM)" },
    { name: "height", label: "Height", type: "number", tab: "uom-volume", section: "VOLUME (METER / KILOGRAM)" },
    { name: "volume", label: "Volume", type: "number", tab: "uom-volume", section: "VOLUME (METER / KILOGRAM)" },
    { name: "gross_weight", label: "Gross Weight", type: "number", tab: "uom-volume", section: "VOLUME (METER / KILOGRAM)" },
    { name: "net_weight", label: "Net Weight", type: "number", tab: "uom-volume", section: "VOLUME (METER / KILOGRAM)" },
    { name: "layers", label: "Layers", type: "number", tab: "uom-volume", section: "VOLUME (METER / KILOGRAM)" },
    { name: "carton_layer", label: "Carton / Layer", type: "number", tab: "uom-volume", section: "VOLUME (METER / KILOGRAM)" },

    // Manufacture & Validation Tab - Manufacturer
    { name: "harmonize_code", label: "Harmonize Code", dropdownParam: "DROP_DOWN_HARMONIZE", dropdownCodeMap: { prin_code: "code1", group_code: "code2", brand_code: "code3" }, tab: "manufacture-validation", section: "MANUFACTURER" },
    { name: "imco_code", label: "IMCO Code", tab: "manufacture-validation", section: "MANUFACTURER" },
    { name: "manufacturer", label: "Manufacturer", dropdownParam: "DROP_DOWN_MANUFACTURER", dropdownCodeMap: { prin_code: "code1" }, tab: "manufacture-validation", section: "MANUFACTURER" },
    { name: "alt_prod_code", label: "Alternate Prod Code", tab: "manufacture-validation", section: "MANUFACTURER" },
    { name: "default_site_ind", label: "Default Site Ind", required: true, dropdownParam: "DROP_DOWN_SITE", tab: "manufacture-validation", section: "MANUFACTURER" },
    { name: "batch_type", label: "Batch Type", type: "number", tab: "manufacture-validation", section: "MANUFACTURER" },

    // Manufacture & Validation Tab - Validation
    { name: "mfg_exp_dt", label: "Mfg/Exp Dt", type: "checkbox", tab: "manufacture-validation", section: "VALIDATION" },
    { name: "supp_cd", label: "Supp. cd", type: "checkbox", tab: "manufacture-validation", section: "VALIDATION" },
    { name: "lot_no", label: "Lot No", type: "checkbox", tab: "manufacture-validation", section: "VALIDATION" },
    { name: "kitting", label: "Kitting", type: "checkbox", tab: "manufacture-validation", section: "VALIDATION" },
    { name: "serialize", label: "Serialize", type: "checkbox", tab: "manufacture-validation", section: "VALIDATION" },
    { name: "receipt_exp_limit", label: "Receipt Exp Limit", type: "number", tab: "manufacture-validation", section: "VALIDATION" },
    { name: "min_period_exp_pick", label: "Min Period Exp Pick", type: "number", tab: "manufacture-validation", section: "VALIDATION" },

    // Category & Product Tab - Category
    { name: "category_abc", label: "Category ABC", type: "select", options: [{ label: "A", value: "A" }, { label: "B", value: "B" }, { label: "C", value: "C" }], tab: "category-product", section: "CATEGORY" },
    { name: "prod_status", label: "Status", required: true, type: "select", options: [{ label: "Active", value: "Active" }, { label: "Inactive", value: "Inactive" }], tab: "category-product", section: "CATEGORY" },
    { name: "prod_type", label: "Product Type", dropdownParam: "DROP_DOWN_PRODUCT_TYPE", tab: "category-product", section: "CATEGORY" },
    { name: "prod_stage", label: "Product Stage", tab: "category-product", section: "CATEGORY" },
    { name: "base_price", label: "Base Price", type: "number", tab: "category-product", section: "CATEGORY" },
    { name: "def_pick_wave", label: "Def. Pick Wave", type: "select", options: [{ label: "Wave 1", value: "1" }, { label: "Wave 2", value: "2" }, { label: "Wave 3", value: "3" }], tab: "category-product", section: "CATEGORY" },
    { name: "shelf_life_days", label: "Shelf Life (Days)", type: "number", tab: "category-product", section: "CATEGORY" },

    // Category & Product Tab - Flags
    { name: "co_packed", label: "Co-packed", type: "checkbox", tab: "category-product", section: "FLAGS" },
    { name: "barcode_print", label: "Barcode Print", type: "checkbox", tab: "category-product", section: "FLAGS" },
    { name: "hazmat_class", label: "Hazmat Class", type: "checkbox", tab: "category-product", section: "FLAGS" },
    { name: "food_ind", label: "Food Ind", type: "checkbox", tab: "category-product", section: "FLAGS" },
    { name: "pharma_ind", label: "Pharma Ind", type: "checkbox", tab: "category-product", section: "FLAGS" },

    // Category & Product Tab - Putaway Preference
    { name: "special_instructions", label: "Special Instructions", type: "textarea", tab: "category-product", section: "PUTAWAY PREFERENCE" },
  ],
  saveEndpoint: (form, { editMode, original }) =>
    editMode ? `product/${original?.prod_code || form.prod_code}` : "product",
  deleteConfig: {
    mode: "rawDelete",
    payload: (row) => [{ prod_code: row.prod_code, prin_code: row.prin_code }],
  },
},
  site: {
    title: "Site Master",
    subtitle: "Maintain site setup with warehouse, division, type, and storage behavior.",
    master: "site",
    gmEndpoint: "siteMaster",
    routeKeys: ["site", "sitemaster", "site_master"],
    keyField: "site_code",
    fields: [
      { name: "site_code", label: "Site Code", required: true, disabledOnEdit: true, width: 140 },
      { name: "site_name", label: "Site Name", required: true, width: 260 },
      { name: "site_ind", label: "Site Indicator", width: 130 },
      { name: "site_type", label: "Site Type", width: 130 },
      { name: "country_code", label: "Country Code", width: 140 },
      { name: "wh_code", label: "Warehouse Code", width: 160 },
      { name: "div_code", label: "Division Code", width: 140 },
      { name: "loc_type", label: "Location Type", width: 150 },
      { name: "site_uom", label: "Site UOM", width: 130 },
      { name: "inc_storage", label: "Include Storage", type: "select", options: yesNo, width: 150 },
      { name: "status", label: "Status", type: "select", options: activeInactive, width: 120 },
    ],
    defaults: { inc_storage: "N", status: "A" },
    deleteConfig: { mode: "disabled", payload: () => null, reason: "Delete endpoint is not registered in the existing backend" },
  },
  warehouse: {
    title: "Warehouse Master",
    subtitle: "Maintain warehouse code, address, country, city, and contact information.",
    master: "warehouse",
    gmEndpoint: "warehouse",
    routeKeys: ["warehouse"],
    keyField: "wh_code",
    fields: [
      { name: "wh_code", label: "Warehouse Code", required: true, disabledOnEdit: true, width: 160 },
      { name: "wh_name", label: "Warehouse Name", required: true, width: 280 },
      { name: "country_code", label: "Country Code", width: 140 },
      { name: "city", label: "City", width: 150 },
      { name: "phone", label: "Phone", width: 150 },
      { name: "address", label: "Address", table: false },
    ],
    deleteConfig: { mode: "disabled", payload: () => null, reason: "Delete endpoint is not registered in the existing backend" },
  },
  location: {
    title: "Location Master",
    subtitle: "Maintain warehouse location code, type, status, physical dimensions, and site.",
    master: "location",
    gmEndpoint: "location",
    routeKeys: ["location"],
    keyField: "location_code",
    fields: [
      { name: "site_code", label: "Site Code", required: true, width: 140 },
      { name: "location_code", label: "Location Code", required: true, disabledOnEdit: true, width: 170 },
      { name: "loc_desc", label: "Description", width: 260 },
      { name: "loc_type", label: "Location Type", width: 150 },
      { name: "loc_stat", label: "Status", width: 120 },
      { name: "aisle", label: "Aisle", width: 110 },
      { name: "column_no", label: "Column", width: 110 },
      { name: "height", label: "Height", type: "number", width: 110 },
      { name: "loc_cbm", label: "CBM", type: "number", width: 110 },
      { name: "loc_wt", label: "Weight", type: "number", width: 110 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.location_code] },
  },
  assetgroup: {
    title: "Asset Group Master",
    subtitle: "Maintain WMS asset group codes and names.",
    master: "assetgroup",
    gmEndpoint: "assetgroup",
    routeKeys: ["assetgroup", "asset_group", "asset-group"],
    keyField: "asset_group_code",
    fields: [
      { name: "asset_group_code", label: "Asset Group Code", required: true, disabledOnEdit: true, width: 180 },
      { name: "asset_group_name", label: "Asset Group Name", required: true, width: 280 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.asset_group_code] },
  },
  currency: {
    title: "Currency Master",
    subtitle: "Maintain currency code, name, exchange rate, division, subdivision, and sign.",
    master: "currency",
    gmEndpoint: "currency",
    keyField: "curr_code",
    fields: [
      { name: "curr_code", label: "Currency Code", required: true, disabledOnEdit: true, width: 130 },
      { name: "curr_name", label: "Currency Name", required: true, width: 220 },
      { name: "ex_rate", label: "Exchange Rate", type: "number", width: 130 },
      { name: "division", label: "Division", required: true, width: 130 },
      { name: "subdivision", label: "Sub Division", type: "number", required: true, width: 130 },
      { name: "curr_sign", label: "Currency Sign", width: 120 },
    ],
    defaults: { ex_rate: 1, subdivision: 100 },
    deleteConfig: { mode: "registered", payload: (row) => [row.curr_code] },
  },
  uom: {
    title: "UOM Master",
    subtitle: "Maintain unit of measurement codes used by product and warehouse transactions.",
    master: "uom",
    gmEndpoint: "uom",
    keyField: "uom_code",
    fields: [
      { name: "uom_code", label: "UOM Code", required: true, disabledOnEdit: true, width: 140 },
      { name: "uom_name", label: "UOM Name", required: true, width: 260 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.uom_code] },
  },
  uoc: {
    title: "UOC Master",
    subtitle: "Maintain unit of charge records for WMS billing activity.",
    master: "uoc",
    gmEndpoint: "uoc",
    keyField: "charge_code",
    fields: [
      { name: "charge_code", label: "Charge Code", required: true, width: 140 },
      { name: "description", label: "Description", required: true, width: 260 },
      { name: "activity_group_code", label: "Activity Group", required: true, width: 170 },
      { name: "charge_type", label: "Charge Type", required: true, width: 140 },
    ],
    mapBeforeSave: (form, { editMode, original }) => ({
      ...form,
      ...(editMode
        ? {
            old_charge_code: original?.charge_code || form.charge_code,
            old_charge_type: original?.charge_type || form.charge_type,
          }
        : {}),
    }),
    deleteConfig: { mode: "registered", payload: (row) => [{ company_code: row.company_code, charge_type: row.charge_type, charge_code: row.charge_code }] },
  },
  brand: {
    title: "Brand Master",
    subtitle: "Maintain brand setup by principal and group with preferred storage ranges.",
    master: "brand",
    gmEndpoint: "brand",
    keyField: "brand_code",
    fields: [
      { name: "brand_code", label: "Brand Code", required: true, disabledOnEdit: true, width: 130 },
      { name: "prin_code", label: "Principal Code", required: true, dropdownParam: "DROP_DOWN_PRINCIPAL", width: 150 },
      { name: "group_code", label: "Group Code", required: true, dropdownParam: "DROP_DOWN_GROUP", dropdownCodeMap: { prin_code: "code1" }, width: 150, disabledWhen: (form) => !form.prin_code },
      { name: "brand_name", label: "Brand Name", required: true, width: 230 },
      { name: "pref_site", label: "Preferred Site", required: false, width: 140 },
      { name: "pref_loc_from", label: "Location From", required: false, width: 150 },
      { name: "pref_loc_to", label: "Location To", required: false, width: 150 },
    ],
    mapBeforeSave: (form, { editMode, original }) => ({
      ...form,
      ...(editMode
        ? {
            old_prin_code: original?.prin_code || form.prin_code,
            old_group_code: original?.group_code || form.group_code,
          }
        : {}),
    }),
    deleteConfig: {
      mode: "registered",
      payload: (row) => [{ company_code: row.company_code, prin_code: row.prin_code, group_code: row.group_code, brand_code: row.brand_code }],
    },
  },
  group: {
    title: "Group Master",
    subtitle: "Maintain product groups by principal with optional storage preferences.",
    master: "group",
    gmEndpoint: "group",
    keyField: "group_code",
    fields: [
      { name: "group_code", label: "Group Code", required: true, disabledOnEdit: true, width: 140 },
      { name: "prin_code", label: "Principal Code", required: true, dropdownParam: "DROP_DOWN_PRINCIPAL", width: 150 },
      { name: "group_name", label: "Group Name", required: true, width: 260 },
    ],
    deleteConfig: {
      mode: "rawDelete",
      payload: (row) => [{ group_code: row.group_code, prin_code: row.prin_code, company_code: row.company_code }],
    },
  },
  line: {
    title: "Line Master",
    subtitle: "Maintain shipping line codes and names.",
    master: "line",
    gmEndpoint: "line",
    keyField: "line_code",
    fields: [
      { name: "line_code", label: "Line Code", required: true, disabledOnEdit: true, width: 140 },
      { name: "line_name", label: "Line Name", required: true, width: 260 },
    ],
    deleteConfig: { mode: "registered", payload: (row) => [row.line_code] },
  },
  vessel: {
    title: "Vessel Master",
    subtitle: "Maintain vessel details, line, contact, and communication information.",
    master: "vessel",
    gmEndpoint: "vessel",
    keyField: "vessel_code",
    fields: [
      { name: "vessel_code", label: "Vessel Code", required: true, width: 140 },
      { name: "vessel_name", label: "Vessel Name", required: true, width: 240 },
      { name: "line_code", label: "Line Code", width: 140 },
      { name: "contact_person", label: "Contact Person", width: 180 },
      { name: "tel_no", label: "Telephone", width: 140 },
      { name: "email", label: "Email", type: "email", width: 220 },
      { name: "address", label: "Address", table: false },
      { name: "fax_no", label: "Fax No", table: false },
    ],
    mapBeforeSave: (form, { editMode, original }) => ({
      ...form,
      ...(editMode
        ? {
            original_vessel_code: original?.vessel_code || form.vessel_code,
            original_company_code: original?.company_code || form.company_code,
          }
        : {}),
    }),
    deleteConfig: { mode: "registered", payload: (row) => [{ vessel_code: row.vessel_code, company_code: row.company_code }] },
  },
  airline: {
    title: "Airline Master",
    subtitle: "Maintain airline codes and names.",
    master: "airline",
    gmEndpoint: "airline",
    keyField: "airline_code",
    fields: [
      { name: "airline_code", label: "Airline Code", required: true, width: 150 },
      { name: "airline_name", label: "Airline Name", required: true, width: 280 },
      { name: "airline_no", label: "Airline No", width: 140 },
      { name: "contact_person", label: "Contact Person", width: 180 },
      { name: "tel_no", label: "Telephone", width: 140 },
      { name: "email", label: "Email", type: "email", width: 220 },
      { name: "address", label: "Address", table: false },
      { name: "fax_no", label: "Fax No", table: false },
    ],
    mapBeforeSave: (form, { editMode, original }) => ({
      ...form,
      ...(editMode ? { old_airline_code: original?.airline_code || form.airline_code } : {}),
    }),
    deleteConfig: { mode: "registered", payload: (row) => [{ airline_code: row.airline_code, company_code: row.company_code }] },
  },

};

export { yesNo };
