import type { ColumnDef } from "@tanstack/react-table";
import { Edit2, Eye, FileText, Plus, Save, Trash2, X } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import {
  executeDynamicDelete,
  executeDynamicMutation,
  getDynamicLookup,
  getLookupText,
  getLookupValue,
  LookupRow,
} from "../../api/lookups";
import { Button } from "../../components/ui/Button";
import { DataTable } from "../../components/ui/DataTable";
import { Dialog } from "../../components/ui/Dialog";
import { AutoDismissAlert } from "../../components/ui/AutoDismissAlert";
import { LookupField } from "../../components/ui/LookupField";
import { FinanceListActionsMenu } from "../../components/finance/FinanceListActionsMenu";
import { exportToCsv } from "../../components/ui/ExportCSVButton";
import { useAuth } from "../../state/AuthContext";

type MasterRow = Record<string, string | number>;
type EditorState =
  | { mode: "create"; row?: undefined }
  | { mode: "edit"; row: MasterRow }
  | { mode: "view"; row: MasterRow }
  | null;

type FieldConfig = {
  key: string;
  label: string;
  required?: boolean;
  type?: "text" | "number" | "select" | "lookup";
  maxLength?: number;
  options?: { value: string; label: string }[];
  lookup?: {
    parameter: string;
    valueField: string;
    displayFields: string[];
    columns: { field: string; header: string }[];
  };
};

export type FinanceUtilityMasterConfig = {
  title: string;
  subtitle: string;
  createLabel: string;
  autoGeneratedKeyLabel?: string;
  formColumns?: 1 | 2;
  listParameter: string;
  saveParameter: string;
  deleteParameter: string;
  keyField: string;
  fields: FieldConfig[];
  columns: { key: string; label: string; width?: number }[];
  mapRow?: (row: LookupRow, companyCode: string) => MasterRow;
  deleteKeys?: (row: MasterRow, companyCode: string) => Record<string, string>;
  saveValues?: (form: MasterRow, companyCode: string) => Record<string, string | number>;
};

const defaultDeleteKeys = (keyField: string) => (row: MasterRow, companyCode: string) => ({
  code1: String(row[keyField] || ""),
  code2: companyCode,
});

export const financeUtilityConfigs = {
  assetGroup: {
    title: "Asset Group",
    subtitle: "Asset Master",
    createLabel: "Add Asset Group",
    autoGeneratedKeyLabel: "Asset Group Code",
    listParameter: "AC_ASSETS_GROUP_PAGE",
    saveParameter: "AC_ASSETS_GROUP",
    deleteParameter: "AC_ASSETS_delete_group",
    keyField: "asset_group_code",
    columns: [
      { key: "asset_group_code", label: "Group Code", width: 150 },
      { key: "asset_group_name", label: "Group Name" },
      { key: "dprc_percentage", label: "Depreciation %", width: 140 },
      { key: "dprc_required", label: "Dep. Required", width: 140 },
      { key: "asset_ac_code", label: "Asset A/C", width: 160 },
      { key: "dprc_ac_code", label: "Dep. A/C", width: 160 },
      { key: "accudprc_ac_code", label: "Accum. Dep. A/C", width: 170 },
      { key: "asset_type", label: "Asset Type", width: 130 },
    ],
    fields: [
      { key: "asset_group_name", label: "Asset Group Name", required: true, maxLength: 150 },
      { key: "dprc_percentage", label: "Depreciation %", type: "number" },
      {
        key: "dprc_required",
        label: "Depreciation Required",
        type: "select",
        options: [
          { value: "Y", label: "Yes" },
          { value: "N", label: "No" },
        ],
      },
      {
        key: "asset_ac_code",
        label: "Asset Account",
        type: "lookup",
        lookup: accountLookup("AC_ASSETS_ACCOUNT_CODE_LIST"),
      },
      {
        key: "dprc_ac_code",
        label: "Depreciation Account",
        type: "lookup",
        lookup: accountLookup("AC_ASSETS_DEPRECIATION_ACCOUNT_CODE_LIST"),
      },
      {
        key: "accudprc_ac_code",
        label: "Accumulated Depreciation Account",
        type: "lookup",
        lookup: accountLookup("AC_ASSETS_DEPRECIATION_ACCOUNT_CODE_LIST"),
      },
      { key: "asset_type", label: "Asset Type", maxLength: 20 },
    ],
    saveValues: (form, companyCode) => {
      const values = {
        val1s1: String(form.asset_group_code || ""),
        val1s2: companyCode,
        val1s3: String(form.asset_group_name || ""),
        val1s4: String(form.dprc_required || "N"),
        val1s5: String(form.asset_ac_code || ""),
        val1s6: String(form.dprc_ac_code || ""),
        val1s7: String(form.accudprc_ac_code || ""),
        val1s8: String(form.asset_type || ""),
        val1n1: Number(form.dprc_percentage || 0),
      };

      return values;
    },
  },
  assetSubgroup: {
    title: "Asset Subgroup",
    subtitle: "Asset Master",
    formColumns: 1,
    createLabel: "Add Asset Subgroup",
    autoGeneratedKeyLabel: "Asset Subgroup Code",
    listParameter: "AC_ASSETS_SUBGROUP",
    saveParameter: "AC_ASSETS_SUBGROUP",
    deleteParameter: "AC_ASSETS_delete_subgroup",
    keyField: "asset_subgroup_code",
    columns: [
      { key: "asset_subgroup_code", label: "Subgroup Code", width: 170 },
      { key: "asset_subgroup_name", label: "Subgroup Name" },
    ],
    fields: [
      { key: "asset_subgroup_name", label: "Subgroup Name", required: true, maxLength: 150 },
    ],
    saveValues: (form, companyCode) => ({
      val1s1: String(form.asset_subgroup_code || ""),
      val1s2: companyCode,
      val1s3: String(form.asset_subgroup_name || ""),
    }),
  },
  assetLocation: {
    title: "Asset Location",
    subtitle: "Asset Master",
    createLabel: "Add Location",
    listParameter: "AC_ASSETS_SITE",
    saveParameter: "AC_ASSETS_SITE",
    deleteParameter: "AC_ASSETS_delete_site",
    keyField: "site_code",
    columns: [
      { key: "site_code", label: "Site Code", width: 150 },
      { key: "site_name", label: "Site Name" },
    ],
    fields: [
      { key: "site_code", label: "Site Code", required: true, maxLength: 5 },
      { key: "site_name", label: "Site Name", required: true, maxLength: 150 },
    ],
    mapRow: (row, companyCode) => ({
      site_code: String(getLookupValue(row, "site_code") || getLookupValue(row, "SITE_CODE") || ""),
      site_name: String(getLookupValue(row, "site_name") || getLookupValue(row, "SITE_NAME") || ""),
      company_code: companyCode,
    }),
    deleteKeys: (row, companyCode) => ({
      code1: companyCode,
      code2: String(row.site_code || ""),
    }),
    saveValues: (form, companyCode) => ({
      val1s1: String(form.site_code || ""),
      val1s2: companyCode,
      val1s3: String(form.site_name || ""),
    }),
  },
  prepaidGroup: {
    title: "Prepaid Group",
    subtitle: "Prepaid Master",
    createLabel: "Add Prepaid Group",
    listParameter: "AC_PREPAID_GET_GROUPING",
    saveParameter: "AC_ASSETS_PREPAID_GROUP",
    deleteParameter: "AC_ASSETS_PREPAID_delete_group",
    keyField: "group_code",
    columns: [
      { key: "group_code", label: "Group Code", width: 150 },
      { key: "group_desc", label: "Group Description" },
    ],
    fields: [
      { key: "group_code", label: "Group Code", required: true, maxLength: 35 },
      { key: "group_desc", label: "Group Description", required: true, maxLength: 150 },
    ],
    saveValues: (form, companyCode) => ({
      val1s1: String(form.group_code || ""),
      val1s2: companyCode,
      val1s3: String(form.group_desc || ""),
    }),
  },
} satisfies Record<string, FinanceUtilityMasterConfig>;

/* ------------------------------------------------------------------ */
/*  Page                                                               */
/* ------------------------------------------------------------------ */

export function FinanceUtilityMasterPage({ config }: { config: FinanceUtilityMasterConfig }) {
  const { user } = useAuth();
  const companyCode = user?.company_code || "";
  const loginId = user?.loginid || "";
  const [rows, setRows] = useState<MasterRow[]>([]);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState<{ type: "success" | "error"; message: string } | null>(null);
  const [editor, setEditor] = useState<EditorState>(null);
  const [deleteTarget, setDeleteTarget] = useState<MasterRow | null>(null);

  const loadRows = async (clearNotice = true) => {
    setLoading(true);
    if (clearNotice) setNotice(null);
    try {
      const data = await getDynamicLookup({
        parameter: config.listParameter,
        loginid: loginId,
        code1: companyCode,
        code2: "",
        code3: "",
        code4: "",
        number1: 0,
        number2: 0,
        number3: 0,
        number4: 0,
        date1: null,
        date2: null,
        date3: null,
        date4: null,
      });
      setRows(data.map((row) => (config.mapRow ? config.mapRow(row, companyCode) : normalizeRow(row, config.fields, companyCode, config.keyField))));
    } catch (error) {
      setNotice({ type: "error", message: error instanceof Error ? error.message : `Unable to load ${config.title}` });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void loadRows();
  }, [config.title]);

  const filteredRows = useMemo(() => {
    const term = query.trim().toLowerCase();
    if (!term) return rows;
    return rows.filter((row) => Object.values(row).some((value) => String(value ?? "").toLowerCase().includes(term)));
  }, [query, rows]);

  const columns = useMemo<ColumnDef<MasterRow>[]>(() => [
    ...config.columns.map<ColumnDef<MasterRow>>((column) => ({
      accessorKey: column.key,
      header: column.label,
      size: column.width,
      cell: ({ row, getValue }) =>
        column.key === config.keyField ? (
          <button
            type="button"
            onClick={() => setEditor({ mode: "edit", row: row.original })}
            className="font-semibold text-[#00378C] hover:underline cursor-pointer text-left bg-transparent border-none p-0"
            title="Click to edit"
          >
            {String(getValue() ?? "")}
          </button>
        ) : (
          <span>{String(getValue() ?? "")}</span>
        ),
    })),
    {
      id: "actions",
      header: () => <div className="text-center">Actions</div>,
      enableSorting: false,
      cell: ({ row }) => (
        <div className="flex items-center justify-center gap-1">
          <Button
            size="icon"
            variant="ghost"
            className="h-7 w-7 text-slate-600 hover:text-[#00378C] hover:bg-[#eff6ff] rounded-md"
            title="View"
            onClick={() => setEditor({ mode: "view", row: row.original })}
          >
            <Eye size={15} />
          </Button>
          <Button
            size="icon"
            variant="ghost"
            className="h-7 w-7 text-slate-600 hover:text-[#00378C] hover:bg-[#eff6ff] rounded-md"
            title="Edit"
            onClick={() => setEditor({ mode: "edit", row: row.original })}
          >
            <Edit2 size={15} />
          </Button>
          <Button
            size="icon"
            variant="ghost"
            className="h-7 w-7 text-slate-600 hover:text-red-600 hover:bg-red-50 rounded-md"
            title="Delete"
            onClick={() => setDeleteTarget(row.original)}
          >
            <Trash2 size={15} />
          </Button>
        </div>
      ),
    },
  ], [config]);

  const deleteRow = async () => {
    if (!deleteTarget) return;
    try {
      const deleteKeys = config.deleteKeys || defaultDeleteKeys(config.keyField);
      await executeDynamicDelete({
        parameter: config.deleteParameter,
        loginid: loginId,
        ...deleteKeys(deleteTarget, companyCode),
      });
      setDeleteTarget(null);
      setNotice({ type: "success", message: `${config.title} deleted successfully` });
      await loadRows(false);
    } catch (error) {
      setNotice({ type: "error", message: error instanceof Error ? error.message : `Unable to delete ${config.title}` });
    }
  };

  return (
    <section className="grid gap-2 p-1">
      {editor ? (
        <UtilityEditor
          config={config}
          editor={editor}
          companyCode={companyCode}
          loginId={loginId}
          onClose={() => setEditor(null)}
          onSaved={async () => {
            setEditor(null);
            setNotice({ type: "success", message: `${config.title} saved successfully` });
            await loadRows(false);
          }}
        />
      ) : (
        <>
          {/* ---------- Top Header (compact) ---------- */}
          <div className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 shadow-sm">
            <div className="flex min-w-0 items-center gap-2.5">
              <div className="flex h-7 w-7 items-center justify-center rounded-md bg-[#00378C]/10 text-[#00378C]">
                <FileText size={14} />
              </div>
              <h1 className="m-0 truncate text-[15px] font-semibold tracking-tight text-slate-900">
                {config.title}
              </h1>
            </div>
          </div>

          <AutoDismissAlert notice={notice} onClose={() => setNotice(null)} />

          {/* ---------- LIST ---------- */}
          <DataTable
            columns={columns}
            data={filteredRows}
            title={loading ? "Loading" : `${filteredRows.length.toLocaleString()} Records`}
            searchValue={query}
            onSearchChange={setQuery}
            searchPlaceholder={`Search ${config.title.toLowerCase()}...`}
            loading={loading}
            emptyText={`No ${config.title.toLowerCase()} records found`}
            height="calc(100dvh - 150px)"
            minWidth={Math.max(760, config.columns.reduce((total, column) => total + (column.width || 210), 120))}
            density="grid"
            enablePagination={false}
            enableExport={false}
            actionButton={
              <div className="flex items-center gap-2">
                <Button
                  type="button"
                  onClick={() => {
                    setNotice(null);
                    setEditor({ mode: "create" });
                  }}
                  className="h-8 gap-1.5 bg-[#00378C] text-white hover:bg-[#002d72] shadow-xs text-xs font-semibold px-3.5 rounded-lg"
                >
                  <Plus size={14} strokeWidth={2.5} /> Add
                </Button>
                <FinanceListActionsMenu
                  fyPeriod=""
                  fyPeriods={[]}
                  onFyPeriodChange={() => {}}
                  onExport={() =>
                    exportToCsv(
                      filteredRows,
                      columns,
                      `${config.title.toLowerCase().replace(/\s+/g, "-")}-${new Date().toISOString().slice(0, 10)}.csv`,
                    )
                  }
                  onRefresh={() => void loadRows(false)}
                />
              </div>
            }
            getRowId={(row, index) => `${String(row[config.keyField] || index)}_${index}`}
          />
        </>
      )}

      {/* ---------- DELETE CONFIRM ---------- */}
      <Dialog
        open={Boolean(deleteTarget)}
        compact
        tone="danger"
        title={`Delete ${config.title}`}
        description="This action cannot be undone."
        onClose={() => setDeleteTarget(null)}
        footer={
          <>
            <Button variant="outline" onClick={() => setDeleteTarget(null)}>
              Close
            </Button>
            <Button variant="destructive" onClick={() => void deleteRow()}>
              Delete
            </Button>
          </>
        }
      >
        <p className="m-0 text-sm text-muted-foreground">
          Delete <strong>{String(deleteTarget?.[config.keyField] || "")}</strong>?
        </p>
      </Dialog>
    </section>
  );
}

/* ------------------------------------------------------------------ */
/*  Editor (in-page, same layout as Budget Version)                    */
/* ------------------------------------------------------------------ */

function UtilityEditor({
  config,
  editor,
  companyCode,
  loginId,
  onClose,
  onSaved,
}: {
  config: FinanceUtilityMasterConfig;
  editor: Exclude<EditorState, null>;
  companyCode: string;
  loginId: string;
  onClose: () => void;
  onSaved: () => Promise<void>;
}) {
  const readOnly = editor.mode === "view";
  const isEdit = editor.mode === "edit";
  const [form, setForm] = useState<MasterRow>(() => ({
    ...Object.fromEntries(config.fields.map((field) => [field.key, field.type === "number" ? 0 : ""])),
    company_code: companyCode,
    ...(editor.row || {}),
  }));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const formId = `${config.keyField}-form`;

  const setField = (key: string, value: string | number) => {
    setForm((prev) => ({ ...prev, [key]: value }));
  };

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();
    if (readOnly) return;
    const missing = config.fields.find((field) => field.required && !String(form[field.key] || "").trim());
    if (missing) {
      setError(`${missing.label} is required.`);
      return;
    }

    setError("");
    setSaving(true);
    try {
      await executeDynamicMutation({
        parameter: config.saveParameter,
        loginid: loginId,
        ...(config.saveValues ? config.saveValues(form, companyCode) : {}),
      });
      await onSaved();
    } catch (err) {
      setError(err instanceof Error ? err.message : `Unable to save ${config.title}`);
    } finally {
      setSaving(false);
    }
  };

  const pageTitle =
    editor.mode === "create"
      ? `New ${config.title}`
      : editor.mode === "edit"
        ? `Edit ${config.title}`
        : `View ${config.title}`;

  const gridClass =
    config.formColumns === 1
      ? "grid grid-cols-1 gap-x-3 gap-y-2.5 max-w-md"
      : "grid grid-cols-2 lg:grid-cols-4 gap-x-3 gap-y-2.5";

  return (
    <>
      {/* ---------- Top Header (compact) ---------- */}
      <div className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 shadow-sm">
        <div className="flex min-w-0 items-center gap-2.5">
          <div className="flex h-7 w-7 items-center justify-center rounded-md bg-[#00378C]/10 text-[#00378C]">
            <FileText size={14} />
          </div>
          <h1 className="m-0 truncate text-[15px] font-semibold tracking-tight text-slate-900">
            {pageTitle}
          </h1>
        </div>

        <div className="flex items-center gap-1.5">
          {!readOnly && (
            <Button
              type="submit"
              form={formId}
              disabled={saving}
              className="h-7 gap-1 bg-[#00378C] text-white hover:bg-[#002d72] shadow-sm text-xs font-semibold px-3 rounded-md"
            >
              <Save size={13} /> Save
            </Button>
          )}
          <Button
            type="button"
            variant="outline"
            size="icon"
            onClick={onClose}
            disabled={saving}
            aria-label="Close"
            title="Close"
            className="h-7 w-7 rounded-md"
          >
            <X size={14} />
          </Button>
        </div>
      </div>

      {/* ---------- EDITOR – fits on one screen ---------- */}
      <form id={formId} className="flex flex-col gap-2" onSubmit={handleSubmit}>
        {error && (
          <div className="rounded-md border border-red-200 bg-red-50 px-3 py-1.5 text-xs font-medium text-red-700">
            {error}
          </div>
        )}

        <div className="rounded-lg border border-slate-200 bg-white shadow-sm overflow-hidden">
          {/* Section Header – very compact */}
          <div className="flex items-center gap-2 border-b border-slate-100 bg-slate-50/70 px-3 py-1.5">
            <div className="flex h-5 w-5 items-center justify-center rounded bg-[#00378C]/10 text-[#00378C]">
              <FileText size={12} />
            </div>
            <h3 className="m-0 text-xs font-semibold text-slate-800">{config.title} Details</h3>
          </div>

          {/* Form Body – single tight block */}
          <div className="p-3">
            {config.autoGeneratedKeyLabel && (
              <div className="mb-2.5 flex items-center justify-between rounded-md border border-slate-200 bg-slate-50/70 px-2.5 py-1.5">
                <div className="text-left">
                  <p className="m-0 text-[11px] font-medium text-slate-600">{config.autoGeneratedKeyLabel}</p>
                  <p className="m-0 text-sm font-semibold text-slate-900">
                    {String(form[config.keyField] || "Autogenerated")}
                  </p>
                </div>
              </div>
            )}

            <div className={gridClass}>
              {config.fields.map((field) => (
                <UtilityField
                  companyCode={companyCode}
                  disabled={readOnly || (isEdit && field.key === config.keyField)}
                  field={field}
                  key={field.key}
                  value={form[field.key]}
                  onChange={(value) => setField(field.key, value)}
                />
              ))}
            </div>
          </div>
        </div>
      </form>
    </>
  );
}

/* ------------------------------------------------------------------ */
/*  Field – ultra compact (same look as Budget Version FormField)      */
/* ------------------------------------------------------------------ */

const inputClass =
  "h-7 w-full rounded-md border border-slate-200 bg-white px-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-[#00378C] focus:outline-none focus:ring-1 focus:ring-[#00378C]/30 disabled:bg-slate-50 disabled:text-slate-500";

function UtilityField({
  field,
  value,
  disabled,
  companyCode,
  onChange,
}: {
  field: FieldConfig;
  value: string | number | undefined;
  disabled?: boolean;
  companyCode: string;
  onChange: (value: string | number) => void;
}) {
  const label = (
    <label className="mb-0.5 block text-[11px] font-medium text-slate-600 text-left">
      {field.label}
      {field.required && <span className="ml-0.5 text-red-500">*</span>}
    </label>
  );

  if (field.type === "select") {
    return (
      <div className="flex flex-col">
        {label}
        <select
          value={String(value || "")}
          onChange={(event) => onChange(event.target.value)}
          disabled={disabled}
          className={inputClass}
        >
          <option value="">Select</option>
          {(field.options || []).map((option) => (
            <option key={option.value} value={option.value}>{option.label}</option>
          ))}
        </select>
      </div>
    );
  }

  if (field.type === "lookup" && field.lookup) {
    return (
      <LookupField
        label={`${field.label}${field.required ? " *" : ""}`}
        value={String(value || "")}
        displayValue={String(value || "")}
        columns={field.lookup.columns}
        valueField={field.lookup.valueField}
        displayFields={field.lookup.displayFields}
        disabled={disabled}
        loadOptions={() =>
          getDynamicLookup({
            parameter: field.lookup!.parameter,
            code1: companyCode,
            code2: "",
            code3: "",
            code4: "",
            number1: 0,
            number2: 0,
            number3: 0,
            number4: 0,
            date1: null,
            date2: null,
            date3: null,
            date4: null,
          })
        }
        onChange={(nextValue, row) => onChange(nextValue || (row ? getLookupText(row, field.lookup!.displayFields) : ""))}
      />
    );
  }

  return (
    <div className="flex flex-col">
      {label}
      <input
        type={field.type === "number" ? "number" : "text"}
        value={String(value ?? "")}
        maxLength={field.maxLength}
        onChange={(event) => onChange(field.type === "number" ? Number(event.target.value || 0) : event.target.value)}
        disabled={disabled}
        className={inputClass}
      />
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

function normalizeRow(row: LookupRow, fields: FieldConfig[], companyCode: string, keyField?: string): MasterRow {
  return {
    ...Object.fromEntries(fields.map((field) => [field.key, getLookupValue(row, field.key)])),
    ...(keyField ? { [keyField]: getLookupValue(row, keyField) } : {}),
    company_code: String(getLookupValue(row, "company_code") || companyCode),
  };
}

function accountLookup(parameter: string) {
  return {
    parameter,
    valueField: "ac_code",
    displayFields: ["ac_code", "ac_name"],
    columns: [
      { field: "ac_code", header: "A/C Code" },
      { field: "ac_name", header: "A/C Name" },
    ],
  };
}