import { FormEvent, useState } from "react";
import { executeDynamicMutation, getDynamicLookup, LookupRow } from "../../api/lookups";
import { AutoDismissAlert } from "../../components/ui/AutoDismissAlert";
import { Card, CardContent, CardHeader } from "../../components/ui/Card";
import { Input } from "../../components/ui/Input";
import { LookupField } from "../../components/ui/LookupField";
import { useAuth } from "../../state/AuthContext";

const Account_AC_CODE_Serach = "Account_AC_CODE_Serach";

//   P_VAL1S1 : EXPENSE_CODE  (blank on insert -> autogenerated in Oracle)
//   P_VAL1S2 : COMPANY_CODE
//   P_VAL1S3 : EXPENSE_NAME
//   P_VAL1S4 : AC_CODE
//   P_VAL1S5 : USER_ID
const PURCHASE_SALE_MSE_EXPENSES = "PURCHASE_SALE_MSE_EXPENSES";

export type TExpenseMaster = {
  expense_code?: string;
  expense_name?: string;
  ac_code?: string;
  ac_name?: string;
  user_id?: string;
  user_dt?: string;
  date1?: string | null;
};

type FormMode = "add" | "edit" | "view";

type Props = {
  mode: FormMode;
  existingData?: Partial<TExpenseMaster>;
  onClose: (shouldRefetch?: boolean) => void;
  onSavingChange?: (saving: boolean) => void;
};

const EMPTY: TExpenseMaster = {
  expense_code: "",
  expense_name: "",
  ac_code: "",
  ac_name: "",
  user_id: "",
  user_dt: "",
};

const accountColumns = [
  { field: "ac_code", header: "A/C Code" },
  { field: "ac_name", header: "A/C Name" },
];

export function AddExpenseMasterForm({ mode, existingData, onClose, onSavingChange }: Props) {
  const { user } = useAuth();
  const readonly = mode === "view";
  const isEdit = mode === "edit";
  const companyCode = user?.company_code ?? "";

  const [form, setForm] = useState<TExpenseMaster>(() => ({ ...EMPTY, ...existingData }));
  const [errors, setErrors] = useState<Partial<Record<keyof TExpenseMaster, string>>>({});
  const [apiError, setApiError] = useState("");

  const setField = (field: keyof TExpenseMaster, value: string) =>
    setForm((prev) => ({ ...prev, [field]: value }));

  const validate = (): boolean => {
    const next: Partial<Record<keyof TExpenseMaster, string>> = {};
    if (!form.expense_name?.trim()) next.expense_name = "Expense Name is required";
    setErrors(next);
    return Object.keys(next).length === 0;
  };

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();
    if (readonly) return;
    if (!validate()) return;

    onSavingChange?.(true);
    setApiError("");
    try {
      await executeDynamicMutation({
        parameter: PURCHASE_SALE_MSE_EXPENSES,
        loginid: user?.loginid ?? "ADMIN",
        val1s1: isEdit ? form.expense_code ?? "" : "",
        val1s2: companyCode,
        val1s3: form.expense_name?.trim() ?? "",
        val1s4: form.ac_code ?? "",
        val1s5: user?.loginid ?? "ADMIN",
      });

      onClose(true);
    } catch (error) {
      setApiError(error instanceof Error ? error.message : "Unable to save expense master record");
    } finally {
      onSavingChange?.(false);
    }
  };

  return (
    <form className="grid content-start gap-4" id="expense-master-form" onSubmit={handleSubmit}>
      <AutoDismissAlert
        notice={apiError ? { type: "error", message: apiError } : null}
        onClose={() => setApiError("")}
      />

      <Card>
        <CardHeader>
          <div>
            <p className="eyebrow">Expense</p>
            <h2 className="m-0 text-sm font-semibold">Basic Information</h2>
          </div>
        </CardHeader>
        <CardContent className="grid grid-cols-1 gap-x-4 gap-y-4 md:grid-cols-2">
          <label className="field">
            <span>Expense Code</span>
            <Input disabled value={form.expense_code || "Autogenerated"} />
          </label>

          <label className="field">
            <span>
              Expense Name <strong className="text-destructive">*</strong>
            </span>
            <Input
              disabled={readonly}
              value={form.expense_name ?? ""}
              onChange={(e) => setField("expense_name", e.target.value)}
              placeholder="e.g. Office Supplies"
            />
            {errors.expense_name && <span className="mt-0.5 text-xs text-destructive">{errors.expense_name}</span>}
          </label>

          <div className="md:col-span-2">
            <Lookup
              label="A/C Code"
              parameter={Account_AC_CODE_Serach}
              value={form.ac_code ?? ""}
              displayValue={
                form.ac_code && form.ac_name ? `${form.ac_code} - ${form.ac_name}` : form.ac_code ?? ""
              }
              valueField="ac_code"
              displayFields={["ac_code", "ac_name"]}
              columns={accountColumns}
              companyCode={companyCode}
              disabled={readonly}
              onSelect={(value, row) => {
                setField("ac_code", value);
                if (row) setField("ac_name", String(row.ac_name ?? ""));
              }}
            />
          </div>
        </CardContent>
      </Card>
    </form>
  );
}

function Lookup({
  label,
  parameter,
  value,
  displayValue,
  valueField,
  displayFields,
  columns,
  companyCode,
  disabled,
  onSelect,
}: {
  label: string;
  parameter: string;
  value: string;
  displayValue: string;
  valueField: string;
  displayFields: string[];
  columns: { field: string; header: string }[];
  companyCode: string;
  disabled?: boolean;
  onSelect: (value: string, row: LookupRow | null) => void;
}) {
  return (
    <LookupField
      label={label}
      value={value}
      displayValue={displayValue}
      columns={columns}
      valueField={valueField}
      displayFields={displayFields}
      disabled={disabled}
      loadOptions={() =>
        getDynamicLookup({
          parameter,
          code1: companyCode,
          code2: "",
          code3: "",
          code4: "",
          number1: 0,
          number2: 0,
          number3: 0,
          number4: 0,
          date1: null,
          date2: null,
          date3: null,
          date4: null,
        })
      }
      onChange={onSelect}
    />
  );
}