import { Save, Search } from "lucide-react";
import { FormEvent, useState } from "react";
import { executeDynamicMutation } from "../../api/lookups";
import { AutoDismissAlert } from "../../components/ui/AutoDismissAlert";
import { Button } from "../../components/ui/Button";
import { Card, CardContent, CardHeader } from "../../components/ui/Card";
import { Input } from "../../components/ui/Input";
import { useAuth } from "../../state/AuthContext";

/* ────────────────────────────────────────────────────────────────────────
 * Maps to MSE_SETUP (one row PER COMPANY_CODE):
 *   COMPANY_CODE, DEF_DEPT_CODE, DEF_DIV_CODE, DEF_ZONE_CODE,
 *   ALLOW_NEG_STOCK, ALLOW_NEG_PICK, RESERVE_ON_ORDER, GRN_AUTO_CONFIRM,
 *   DN_AUTO_CONFIRM, ADJUST_AC_CODE, PIN_AUTO_POST, SIN_AUTO_POST,
 *   BASE_DISC_CODE, DUPL_ITEM_PUR, EDIT_GRN_DT, EDIT_DN_DT,
 *   ITEMDESC_EDIT, PLEAD_TIME
 *
 * DEF_DEPT_CODE is a normal editable lookup field here — unlike
 * BRAND_CODE on the Product Brand form, it is NOT autogenerated.
 *
 * DEF_DIV_CODE is rendered as a real <select>, sourced from the
 * ACCOUNT_DIVISION lookup parameter (passed in as `divisions` from the
 * parent page), instead of a code-search popup.
 *
 * TODO (backend): PURCHASE_SALE_MSE_SETUP is a placeholder parameter key
 * for the dynamic INSERT/UPDATE dispatcher. The SELECT for MSE_SETUP was
 * supplied but not the save-side procedure's WHEN branch, so the val1s*
 * slot order below is a best-guess mapping (same column order as the
 * SELECT, USER_ID appended, PLEAD_TIME as the one numeric slot) — confirm
 * the real P_VAL1S* mapping in PROC_BUILD_DYNAMIC_INS_UPD_PURCHASE_SALE
 * before going live, the same way it's documented for PRODBRAND:
 *   P_VAL1S1  : COMPANY_CODE
 *   P_VAL1S2  : DEF_DEPT_CODE
 *   P_VAL1S3  : DEF_DIV_CODE
 *   P_VAL1S4  : DEF_ZONE_CODE
 *   P_VAL1S5  : ALLOW_NEG_STOCK
 *   P_VAL1S6  : ALLOW_NEG_PICK
 *   P_VAL1S7  : RESERVE_ON_ORDER
 *   P_VAL1S8  : GRN_AUTO_CONFIRM
 *   P_VAL1S9  : DN_AUTO_CONFIRM
 *   P_VAL1S10 : ADJUST_AC_CODE
 *   P_VAL1S11 : PIN_AUTO_POST
 *   P_VAL1S12 : SIN_AUTO_POST
 *   P_VAL1S13 : BASE_DISC_CODE
 *   P_VAL1S14 : DUPL_ITEM_PUR
 *   P_VAL1S15 : EDIT_GRN_DT
 *   P_VAL1S16 : EDIT_DN_DT
 *   P_VAL1S17 : ITEMDESC_EDIT
 *   P_VAL1S18 : USER_ID
 *   P_VAL1N1  : PLEAD_TIME
 * ──────────────────────────────────────────────────────────────────── */

const PURCHASE_SALE_MSE_SETUP = "PURCHASE_SALE_MSE_SETUP";

export type YesNo = "Y" | "N";

export type TPurchaseSaleSetup = {
  company_code?: string;
  def_dept_code?: string;
  def_div_code?: string;
  def_zone_code?: string;
  allow_neg_stock?: YesNo;
  allow_neg_pick?: YesNo;
  reserve_on_order?: YesNo;
  grn_auto_confirm?: YesNo;
  dn_auto_confirm?: YesNo;
  adjust_ac_code?: string;
  pin_auto_post?: YesNo;
  sin_auto_post?: YesNo;
  base_disc_code?: string;
  dupl_item_pur?: YesNo;
  edit_grn_dt?: boolean;
  edit_dn_dt?: boolean;
  itemdesc_edit?: boolean;
  plead_time?: string;
};

export type DivisionOption = {
  div_code: string;
  div_name: string;
};

type FormMode = "add" | "edit" | "view";

type Props = {
  mode: FormMode;
  existingData?: Partial<TPurchaseSaleSetup>;
  divisions: DivisionOption[];
  onClose: (shouldRefetch?: boolean) => void;
};

const EMPTY: TPurchaseSaleSetup = {
  company_code: "",
  def_dept_code: "",
  def_div_code: "",
  def_zone_code: "",
  allow_neg_stock: "N",
  allow_neg_pick: "N",
  reserve_on_order: "N",
  grn_auto_confirm: "Y",
  dn_auto_confirm: "Y",
  adjust_ac_code: "",
  pin_auto_post: "Y",
  sin_auto_post: "Y",
  base_disc_code: "",
  dupl_item_pur: "Y",
  edit_grn_dt: false,
  edit_dn_dt: false,
  itemdesc_edit: false,
  plead_time: "",
};

// ── Reusable field pieces ───────────────────────────────────────────────

function YesNoSelect({
  label,
  value,
  onChange,
  disabled,
}: {
  label: string;
  value: YesNo;
  onChange: (v: YesNo) => void;
  disabled?: boolean;
}) {
  return (
    <label className="field">
      <span>{label}</span>
      <select
        className="input"
        value={value}
        disabled={disabled}
        onChange={(e) => onChange(e.target.value as YesNo)}
      >
        <option value="Y">Yes</option>
        <option value="N">No</option>
      </select>
    </label>
  );
}

function DivisionSelect({
  label,
  value,
  options,
  onChange,
  disabled,
  required,
  error,
}: {
  label: string;
  value: string;
  options: DivisionOption[];
  onChange: (v: string) => void;
  disabled?: boolean;
  required?: boolean;
  error?: string;
}) {
  return (
    <label className="field">
      <span>
        {label} {required && <strong className="text-destructive">*</strong>}
      </span>
      <select
        className="input"
        value={value}
        disabled={disabled}
        onChange={(e) => onChange(e.target.value)}
      >
        <option value="">Select division...</option>
        {options.map((opt) => (
          <option key={opt.div_code} value={opt.div_code}>
            {opt.div_code} - {opt.div_name}
          </option>
        ))}
      </select>
      {error && <span className="text-destructive text-xs mt-0.5">{error}</span>}
    </label>
  );
}

function LookupField({
  label,
  value,
  onChange,
  onSearch,
  disabled,
  required,
  error,
}: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  onSearch: () => void;
  disabled?: boolean;
  required?: boolean;
  error?: string;
}) {
  return (
    <label className="field">
      <span>
        {label} {required && <strong className="text-destructive">*</strong>}
      </span>
      <div className="flex items-center gap-1">
        <Input
          disabled={disabled}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder={`Enter ${label.toLowerCase()}`}
        />
        <Button type="button" size="icon" variant="outline" title={`Search ${label}`} onClick={onSearch}>
          <Search size={14} />
        </Button>
      </div>
      {error && <span className="text-destructive text-xs mt-0.5">{error}</span>}
    </label>
  );
}

function CheckboxField({
  label,
  checked,
  onChange,
  disabled,
}: {
  label: string;
  checked: boolean;
  onChange: (v: boolean) => void;
  disabled?: boolean;
}) {
  return (
    <label className="flex items-center gap-2 text-sm">
      <input type="checkbox" checked={checked} disabled={disabled} onChange={(e) => onChange(e.target.checked)} />
      {label}
    </label>
  );
}

// ── Form ─────────────────────────────────────────────────────────────────

export function AddPurchaseSaleSetupForm({ mode, existingData, divisions, onClose }: Props) {
  const { user } = useAuth();
  const readonly = mode === "view";
  const isEdit = mode === "edit";
  const companyCode = user?.company_code ?? "";

  const [form, setForm] = useState<TPurchaseSaleSetup>(() => ({ ...EMPTY, ...existingData, company_code: existingData?.company_code || companyCode }));
  const [errors, setErrors] = useState<Partial<Record<keyof TPurchaseSaleSetup, string>>>({});
  const [saving, setSaving] = useState(false);
  const [apiError, setApiError] = useState("");

  const setField = <K extends keyof TPurchaseSaleSetup>(field: K, value: TPurchaseSaleSetup[K]) =>
    setForm((prev) => ({ ...prev, [field]: value }));

  // ── Validation ──────────────────────────────────────────────────────────
  // Dept/Div/Zone codes are the required defaults; everything else has a
  // sane fallback value in EMPTY above.
  const validate = (): boolean => {
    const next: Partial<Record<keyof TPurchaseSaleSetup, string>> = {};
    if (!form.def_dept_code?.trim()) next.def_dept_code = "Default Dept Code is required";
    if (!form.def_div_code?.trim()) next.def_div_code = "Default Div Code is required";
    if (!form.def_zone_code?.trim()) next.def_zone_code = "Default Zone Code is required";
    setErrors(next);
    return Object.keys(next).length === 0;
  };

  // ── Submit ──────────────────────────────────────────────────────────────
  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();
    if (readonly) return;
    if (!validate()) return;

    setSaving(true);
    setApiError("");
    try {
      const leadTimeNum = Number(form.plead_time);

      await executeDynamicMutation({
        parameter: PURCHASE_SALE_MSE_SETUP,
        loginid: user?.loginid ?? "ADMIN",
        val1s1: companyCode,
        val1s2: form.def_dept_code?.trim() ?? "",
        val1s3: form.def_div_code?.trim() ?? "",
        val1s4: form.def_zone_code?.trim() ?? "",
        val1s5: form.allow_neg_stock ?? "N",
        val1s6: form.allow_neg_pick ?? "N",
        val1s7: form.reserve_on_order ?? "N",
        val1s8: form.grn_auto_confirm ?? "N",
        val1s9: form.dn_auto_confirm ?? "N",
        val1s10: form.adjust_ac_code?.trim() ?? "",
        val1s11: form.pin_auto_post ?? "N",
        val1s12: form.sin_auto_post ?? "N",
        val1s13: form.base_disc_code?.trim() ?? "",
        val1s14: form.dupl_item_pur ?? "N",
        val1s15: form.edit_grn_dt ? "Y" : "N",
        val1s16: form.edit_dn_dt ? "Y" : "N",
        val1s17: form.itemdesc_edit ? "Y" : "N",
        val1s18: user?.loginid ?? "ADMIN",
        val1n1: Number.isFinite(leadTimeNum) ? leadTimeNum : 0,
        // isEdit is available if the save procedure needs to distinguish
        // insert vs update explicitly (MSE_SETUP is otherwise a natural
        // upsert keyed on COMPANY_CODE, same as val1s1 above).
      });

      onClose(true);
    } catch (error) {
      setApiError(error instanceof Error ? error.message : "Unable to save purchase/sales setup");
    } finally {
      setSaving(false);
    }
  };

  // Placeholder — wire to your existing code-search / lookup modal.
  const openLookup = (field: string) => {
    setApiError(`Lookup for "${field}" is not wired up yet.`);
  };

  void isEdit;

  // ── UI ──────────────────────────────────────────────────────────────────
  return (
    <div className="flex min-h-[320px] flex-col">
      <form className="grid flex-1 content-start gap-4 overflow-auto p-4" id="purchase-sale-setup-form" onSubmit={handleSubmit}>
        <AutoDismissAlert notice={apiError ? { type: "error", message: apiError } : null} onClose={() => setApiError("")} />

        <Card>
          <CardHeader>
            <div>
              <p className="eyebrow">Purchase/Sales Setup</p>
              <h2 className="m-0 text-sm font-semibold">Company {companyCode || "—"}</h2>
            </div>
          </CardHeader>
          <CardContent className="grid grid-cols-1 gap-x-6 gap-y-4 md:grid-cols-2">
            {/* Left column */}
            <div className="grid gap-4">
              <LookupField
                label="Default Dept Code"
                value={form.def_dept_code ?? ""}
                onChange={(v) => setField("def_dept_code", v)}
                onSearch={() => openLookup("Default Dept Code")}
                disabled={readonly}
                required
                error={errors.def_dept_code}
              />

              <DivisionSelect
                label="Default Div Code"
                value={form.def_div_code ?? ""}
                options={divisions}
                onChange={(v) => setField("def_div_code", v)}
                disabled={readonly}
                required
                error={errors.def_div_code}
              />

              <LookupField
                label="Default Zone Code"
                value={form.def_zone_code ?? ""}
                onChange={(v) => setField("def_zone_code", v)}
                onSearch={() => openLookup("Default Zone Code")}
                disabled={readonly}
                required
                error={errors.def_zone_code}
              />

              <LookupField
                label="Adjustment A/c Code"
                value={form.adjust_ac_code ?? ""}
                onChange={(v) => setField("adjust_ac_code", v)}
                onSearch={() => openLookup("Adjustment A/c Code")}
                disabled={readonly}
              />

              <LookupField
                label="Base Discount Code"
                value={form.base_disc_code ?? ""}
                onChange={(v) => setField("base_disc_code", v)}
                onSearch={() => openLookup("Base Discount Code")}
                disabled={readonly}
              />

              <YesNoSelect
                label="Duplicate Items in Purchase"
                value={form.dupl_item_pur ?? "N"}
                onChange={(v) => setField("dupl_item_pur", v)}
                disabled={readonly}
              />

              <div className="grid gap-2">
                <CheckboxField
                  label="Product Name Editable"
                  checked={!!form.itemdesc_edit}
                  onChange={(v) => setField("itemdesc_edit", v)}
                  disabled={readonly}
                />
                <CheckboxField
                  label="GRN Date Change"
                  checked={!!form.edit_grn_dt}
                  onChange={(v) => setField("edit_grn_dt", v)}
                  disabled={readonly}
                />
                <CheckboxField
                  label="DN Date Change"
                  checked={!!form.edit_dn_dt}
                  onChange={(v) => setField("edit_dn_dt", v)}
                  disabled={readonly}
                />
              </div>
            </div>

            {/* Right column */}
            <div className="grid gap-4">
              <YesNoSelect
                label="Allow Negative Stock"
                value={form.allow_neg_stock ?? "N"}
                onChange={(v) => setField("allow_neg_stock", v)}
                disabled={readonly}
              />
              <YesNoSelect
                label="Allow Negative Pick"
                value={form.allow_neg_pick ?? "N"}
                onChange={(v) => setField("allow_neg_pick", v)}
                disabled={readonly}
              />
              <YesNoSelect
                label="Reserve On Order"
                value={form.reserve_on_order ?? "N"}
                onChange={(v) => setField("reserve_on_order", v)}
                disabled={readonly}
              />
              <YesNoSelect
                label="GRN Auto Confirm"
                value={form.grn_auto_confirm ?? "N"}
                onChange={(v) => setField("grn_auto_confirm", v)}
                disabled={readonly}
              />
              <YesNoSelect
                label="DN Auto Confirm"
                value={form.dn_auto_confirm ?? "N"}
                onChange={(v) => setField("dn_auto_confirm", v)}
                disabled={readonly}
              />
              <YesNoSelect
                label="P.Invoice Auto Post"
                value={form.pin_auto_post ?? "N"}
                onChange={(v) => setField("pin_auto_post", v)}
                disabled={readonly}
              />
              <YesNoSelect
                label="Sales Invoice Auto Post"
                value={form.sin_auto_post ?? "N"}
                onChange={(v) => setField("sin_auto_post", v)}
                disabled={readonly}
              />
              <label className="field">
                <span>Purchase Lead Time</span>
                <Input
                  type="number"
                  min={0}
                  disabled={readonly}
                  value={form.plead_time ?? ""}
                  onChange={(e) => setField("plead_time", e.target.value)}
                  placeholder="Days"
                />
              </label>
            </div>
          </CardContent>
        </Card>
      </form>

      <div className="flex items-center justify-end gap-2 border-t bg-card p-4">
        <Button variant="outline" onClick={() => onClose(false)}>
          {readonly ? "Close" : "Cancel"}
        </Button>
        {!readonly && (
          <Button disabled={saving} type="submit" form="purchase-sale-setup-form">
            {saving ? <span className="spinner small" /> : <Save size={15} />} {saving ? "Saving..." : "Save"}
          </Button>
        )}
      </div>
    </div>
  );
}