import { FormEvent, useState } from "react";
import { executeDynamicMutation } from "../../api/lookups";
import { AutoDismissAlert } from "../../components/ui/AutoDismissAlert";
import { Card, CardContent, CardHeader } from "../../components/ui/Card";
import { Input } from "../../components/ui/Input";
import { useAuth } from "../../state/AuthContext";

// P_VAL1S1 : BRAND_CODE (blank on insert -> autogenerated in Oracle)
// P_VAL1S2 : COMPANY_CODE
// P_VAL1S3 : BRAND_NAME
// P_VAL1S4 : USER_ID
const PURCHASE_SALE_MSE_PRODBRAND = "PURCHASE_SALE_MSE_PRODBRAND";

export type TProductBrand = {
  brand_code?: string;
  brand_name?: string;
  user_id?: string;
  user_dt?: string;
};

type FormMode = "add" | "edit" | "view";

type Props = {
  mode: FormMode;
  existingData?: Partial<TProductBrand>;
  onClose: (shouldRefetch?: boolean) => void;
  onSavingChange?: (saving: boolean) => void;
};

const EMPTY: TProductBrand = {
  brand_code: "",
  brand_name: "",
  user_id: "",
  user_dt: "",
};

export function AddProductBrandForm({ mode, existingData, onClose, onSavingChange }: Props) {
  const { user } = useAuth();
  const readonly = mode === "view";
  const isEdit = mode === "edit";
  const companyCode = user?.company_code ?? "";

  const [form, setForm] = useState<TProductBrand>(() => ({ ...EMPTY, ...existingData }));
  const [errors, setErrors] = useState<Partial<Record<keyof TProductBrand, string>>>({});
  const [apiError, setApiError] = useState("");

  const setField = (field: keyof TProductBrand, value: string) =>
    setForm((prev) => ({ ...prev, [field]: value }));

  const validate = (): boolean => {
    const next: Partial<Record<keyof TProductBrand, string>> = {};
    if (!form.brand_name?.trim()) next.brand_name = "Brand Name is required";
    setErrors(next);
    return Object.keys(next).length === 0;
  };

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();
    if (readonly) return;
    if (!validate()) return;

    onSavingChange?.(true);
    setApiError("");
    try {
      await executeDynamicMutation({
        parameter: PURCHASE_SALE_MSE_PRODBRAND,
        loginid: user?.loginid ?? "ADMIN",
        val1s1: isEdit ? form.brand_code ?? "" : "",
        val1s2: companyCode,
        val1s3: form.brand_name?.trim() ?? "",
        val1s4: user?.loginid ?? "ADMIN",
      });

      onClose(true);
    } catch (error) {
      setApiError(error instanceof Error ? error.message : "Unable to save product brand record");
    } finally {
      onSavingChange?.(false);
    }
  };

  return (
    <form className="grid content-start gap-4" id="brand-master-form" onSubmit={handleSubmit}>
      <AutoDismissAlert
        notice={apiError ? { type: "error", message: apiError } : null}
        onClose={() => setApiError("")}
      />

      <Card>
        <CardHeader>
          <div>
            <p className="eyebrow">Product Brand</p>
            <h2 className="m-0 text-sm font-semibold">Basic Information</h2>
          </div>
        </CardHeader>
        <CardContent className="grid grid-cols-1 gap-x-4 gap-y-4 md:grid-cols-2">
          <label className="field">
            <span>Brand Code</span>
            <Input disabled value={form.brand_code || "Autogenerated"} />
          </label>

          <label className="field">
            <span>
              Brand Name <strong className="text-destructive">*</strong>
            </span>
            <Input
              disabled={readonly}
              value={form.brand_name ?? ""}
              onChange={(e) => setField("brand_name", e.target.value)}
              placeholder="e.g. Samsung"
            />
            {errors.brand_name && <span className="mt-0.5 text-xs text-destructive">{errors.brand_name}</span>}
          </label>
        </CardContent>
      </Card>
    </form>
  );
}